### PR TITLE
Issue 183: Set upgrade error status

### LINKED ISSUE #186: Upgrade process fails to detect the error/failure and fails to set the `Error` status to `True`
**Upgrade process waits indefinitely for the failed pod to recover and not updating the `Error` and `upgrading` status appropriately**

When I tried to simulate upgrade failure scenario by upgrading Pravega cluster version from `0.5.0-2222.8ba543`1 to `0.5.0-2222` (Here 0.5.0-2222 docker image is not existing), upgrade process failing to detect the `ImagePullBackOff`  Error on the `Bookie-0` pod.

I was expecting the upgrade process will detect the failure/timeout and update the status of `Error` to `True` and `upgrading` status to `false`. But the upgrade process is waiting indefinitely (tested for more than a day) for `Bookie-0` pod to recover and not updating the status of upgrade failure.

**kubectl describe PravegaCluster output**
```
Status:
  Conditions:
    Last Transition Time:  2019-05-15T07:57:10Z
    Last Update Time:      2019-05-15T07:57:10Z
    Status:                True
    Type:                  Upgrading
    Last Transition Time:  2019-05-15T07:58:28Z
    Last Update Time:      2019-05-15T07:58:28Z
    Status:                False
    Type:                  PodsReady
    Status:                False
    Type:                  Error
  Current Replicas:        9
  Current Version:         0.5.0-2222.8ba5431
  Members:
    Ready:
      pravega-bookie-1
      pravega-bookie-2
      pravega-bookie-3
      pravega-pravega-controller-7f89bff94d-sct8n
      pravega-pravega-controller-7f89bff94d-wkdnk
      pravega-pravega-segmentstore-0
      pravega-pravega-segmentstore-1
      pravega-pravega-segmentstore-2
    Unready:
      pravega-bookie-0
  Ready Replicas:  8
  Replicas:        9
  Target Version:  0.5.0-2222
Events:            <none>
```
```
# kubectl get pravegacluster
NAME      VERSION              DESIRED VERSION   DESIRED MEMBERS   READY MEMBERS   AGE
pravega   0.5.0-2222.8ba5431                     9                 8               3d
```
**Pod status**
```
[root@master May-17]# kubectl get po  --all-namespaces
NAMESPACE     NAME                                                 READY   STATUS             RESTARTS   AGE
default       boiling-ragdoll-pravega-operator-7695d64cf-rvzdf     1/1     Running            0          4d
default       pravega-benchmark                                    1/1     Running            0          3d3h
default       pravega-bookie-0                                     0/1     ImagePullBackOff   0          2d5h
default       pravega-bookie-1                                     1/1     Running            0          3d1h
default       pravega-bookie-2                                     1/1     Running            0          3d1h
default       pravega-bookie-3                                     1/1     Running            0          3d1h
default       pravega-pravega-controller-7f89bff94d-sct8n          1/1     Running            0          3d1h
default       pravega-pravega-controller-7f89bff94d-wkdnk          1/1     Running            0          3d1h
default       pravega-pravega-segmentstore-0                       1/1     Running            0          3d1h
default       pravega-pravega-segmentstore-1                       1/1     Running            0          3d1h
default       pravega-pravega-segmentstore-2                       1/1     Running            0          3d1h
default       pravega-zk-0                                         1/1     Running            0          3d23h
default       pravega-zk-1                                         1/1     Running            0          3d23h
default       pravega-zk-2                                         1/1     Running            0          3d23h
default       shaka-zulu-nfs-client-provisioner-59d7f8f84c-tvh7w   1/1     Running            0          3d23h
default       zookeeper-operator-685bfcbbc5-7r48t                  1/1     Running            0          3d23h
```

**Logs from Pravega-operator:**
```
time="2019-05-15T07:57:10Z" level=info msg="syncing cluster version from 0.5.0-2222.8ba5431 to 0.5.0-2222"
ng statefulset (pravega-bookie) template image to 'devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2222'"
time="2019-05-15T07:57:27Z" level=info msg="Reconciling PravegaCluster default/prtime="2019-05-15T07:57:10Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:57:10Z" level=info msg="updating statefulset (pravega-bookie) template image to 'devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2222'"
time="2019-05-15T07:57:27Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:57:27Z" level=info msg="statefulset (pravega-bookie) status: 0 updated, 4 ready, 4 target"
time="2019-05-15T07:57:27Z" level=info msg="upgrading pod: pravega-bookie-0"
time="2019-05-15T07:57:57Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:57:58Z" level=info msg="statefulset (pravega-bookie) status: 0 updated, 4 ready, 4 target"
time="2019-05-15T07:57:58Z" level=info msg="upgrading pod: pravega-bookie-0"
time="2019-05-15T07:58:28Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:58:28Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:58:28Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:58:28Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:58:58Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:58:58Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:59:28Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:59:28Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:59:58Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
..............
...............
time="2019-05-17T12:47:59Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:47:59Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:48:29Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:48:29Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:48:59Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:48:59Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:49:29Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:49:30Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:50:00Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:50:00Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:50:30Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:50:30Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:51:00Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:51:00Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:51:30Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:51:30Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
 ```

### PR DESCRIPTION
**Pull request by Tristan1900**
Signed-off-by: wenqimou <452787782@qq.com>

### Change log description

This PR will set Pravega upgrade condition to false if there are errors happen during the upgrade. The way to detect error is to see if there is any progress has been made during a timeout. 

### Purpose of the change

Fix #186 

### What the code does

The code will put the updated pod number into the `upgrading condition` message. When checking the upgrade status, it will check if the updated pod number has changed, if it has changed, then update the changed number, which will also add a timestamp to the `upgrading condition`. If nothing changed, it will compare the current time with the timestamp in the condition, if the difference exceeds 10 minutes, it will return an error indicating that there is no progress for the last 10 minutes and the upgrade can be considered as failed.

### How to verify it

TBD

### CODE REVIEW

File: pkg/controller/pravegacluster/upgrade.go [hunk 1]
```diff
@@ -378,3 +425,18 @@ func (r *ReconcilePravegaCluster) getPodsWithVersion(sts *appsv1.StatefulSet, ve
 	}
 	return pods, nil
 }
+
+func checkUpgradeCondition(p *pravegav1alpha1.PravegaCluster, reason string, updatedReplicas int32) error {
```
Comment (pbelgundi) [inline pkg/controller/pravegacluster/upgrade.go]: I think we should check the delay at pod level instead of checking at sts level.
If there are many replicas in the sts and each one takes a little extra delay we could easily run out of our threshold.

Comment (pbelgundi) [reply pkg/controller/pravegacluster/upgrade.go]: Threshold should be at pod level, assuming it would never take more than 10 mins to upgrade/deploy a single pod, if we realize it is taking us longer than that, we bail out... and fail the upgrade.

**Comment by pbelgundi** [comment]
It would help to add a section to upgrade documentation, explaining how we handle upgrade failures and mechanisms detecting a stuck Upgrade and to move the cluster into UpgradeFailed state.

File: pkg/controller/pravegacluster/upgrade.go [hunk 2]
```diff
@@ -378,3 +425,18 @@ func (r *ReconcilePravegaCluster) getPodsWithVersion(sts *appsv1.StatefulSet, ve
...
+	_, lastCondition := p.Status.GetClusterCondition(pravegav1alpha1.ClusterConditionUpgrading)
+	if lastCondition.Reason == reason && lastCondition.Message != string(updatedReplicas) {
```
Comment (pbelgundi) [inline pkg/controller/pravegacluster/upgrade.go]: Here we seem to be checking against time since cluster went into "upgrading" state.
That is not correct. We need to check against time since this sts went into upgrading state.

File: pkg/controller/pravegacluster/upgrade.go (hunk 1 above)
Comment (Tristan1900) [reply pkg/controller/pravegacluster/upgrade.go]: The sts will help us managing pods. If a pod is updated, it will show up in the status of sts and this method will update the status in Pravega, see the last line. The `SetUpgradingConditionTrue` will update the upgrading condition with a message showing the number of updated replicas, if that number of updated replicas change, the upgrade condition field `updateTimestamp` will be updated to `now`. So it is not calculating the finishing time of the whole sts, the time is updated when the updated replicas change.

File: pkg/controller/pravegacluster/upgrade.go (hunk 2 above)
Comment (Tristan1900) [reply pkg/controller/pravegacluster/upgrade.go]: This is not. Please check the last comment.

File: pkg/apis/pravega/v1alpha1/status.go [hunk 3]
```diff
@@ -102,7 +107,7 @@ func (ps *ClusterStatus) SetPodsReadyConditionFalse() {
 	ps.setClusterCondition(*c)
 }
 
-func (ps *ClusterStatus) SetUpgradingConditionTrue() {
+func (ps *ClusterStatus) SetUpgradingConditionTrue(reason, message string) {
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/apis/pravega/v1alpha1/status.go]: It is used in `checkUpgradeCondition`

File: pkg/apis/pravega/v1alpha1/status.go [hunk 4]
```diff
@@ -22,6 +22,11 @@ const (
 	ClusterConditionPodsReady ClusterConditionType = "PodsReady"
 	ClusterConditionUpgrading                      = "Upgrading"
 	ClusterConditionError                          = "Error"
+
+	// Reasons for cluster upgrading condition
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/apis/pravega/v1alpha1/status.go]: A little confused, this is the `reason`. See the name `UpgradingControllerReason`.

File: pkg/controller/pravega/pravega_controller.go [hunk 5]
```diff
@@ -35,8 +35,9 @@ func MakeControllerDeployment(p *api.PravegaCluster) *appsv1.Deployment {
 			Labels:    util.LabelsForController(p),
 		},
 		Spec: appsv1.DeploymentSpec{
-			Replicas: &p.Spec.Pravega.ControllerReplicas,
-			Template: MakeControllerPodTemplate(p),
+			ProgressDeadlineSeconds: func(i int32) *int32 { return &i }(600),
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/controller/pravega/pravega_controller.go]: yeah we could do that

File: pkg/controller/pravegacluster/upgrade.go [hunk 6]
```diff
@@ -175,6 +176,15 @@ func (r *ReconcilePravegaCluster) syncControllerVersion(p *pravegav1alpha1.Prave
 	log.Printf("deployment (%s) status: %d updated, %d ready, %d target", deploy.Name,
 		deploy.Status.UpdatedReplicas, deploy.Status.ReadyReplicas, deploy.Status.Replicas)
 
+	// Check whether the controller upgrade fail to have progress.
+	for _, v := range deploy.Status.Conditions {
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/controller/pravegacluster/upgrade.go]: My mistake, the if statement should be `sts.Status.UpdatedReplicas == sts.Status.Replicas && sts.Status.UpdatedReplicas == sts.Status.ReadyReplicas`. Will modify now

[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/controller/pravegacluster/upgrade.go]: Got it. I agree it is more intuitive to do that.

File: pkg/controller/pravega/pravega_controller.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/controller/pravega/pravega_controller.go]: Just try a little bit, it doesn't work. Seems Go doesn't allow to use the address of a numeric constant

File: pkg/webhook/webhook_test.go [hunk 7]
```diff
@@ -281,7 +281,7 @@ var _ = Describe("Admission webhook", func() {
 				p.Spec = v1alpha1.ClusterSpec{
 					Version: "0.5.0-001",
 				}
-				p.Status.SetUpgradingConditionTrue()
+				p.Status.SetUpgradingConditionTrue("", "")
```
Comment (pbelgundi) [inline pkg/webhook/webhook_test.go]: Please add unit tests to cover all failure scenarios.

File: pkg/controller/pravega/pravega_controller.go (hunk 5 above)
Comment (pbelgundi) [inline pkg/controller/pravega/pravega_controller.go]: We could use a local variable instead of this function. That would keep code simple.

File: pkg/apis/pravega/v1alpha1/status.go [hunk 8]
```diff
@@ -22,6 +22,11 @@ const (
...
+	UpgradingControllerReason   = "UpgradingController"
```
Comment (pbelgundi) [inline pkg/apis/pravega/v1alpha1/status.go]: I think it would be good to have the string as "Updating Controller" since same string can be used for upgrade as well as rollback on the component.

File: pkg/controller/pravega/pravega_segmentstore.go [hunk 9]
```diff
@@ -44,7 +44,7 @@ func MakeSegmentStoreStatefulSet(pravegaCluster *api.PravegaCluster) *appsv1.Sta
 			Replicas:            &pravegaCluster.Spec.Pravega.SegmentStoreReplicas,
 			PodManagementPolicy: appsv1.OrderedReadyPodManagement,
 			UpdateStrategy: appsv1.StatefulSetUpdateStrategy{
-				Type: appsv1.RollingUpdateStatefulSetStrategyType,
+				Type: appsv1.OnDeleteStatefulSetStrategyType,
```
Comment (pbelgundi) [inline pkg/controller/pravega/pravega_segmentstore.go]: Please update upgrade documentation (upgrade.md) to reflect that Segment Store upgrade strategy has been changed from "Rolling Update" to "OnDelete".

File: pkg/controller/pravega/pravega_controller.go (hunk 5 above)
Comment (Tristan1900) [reply pkg/controller/pravega/pravega_controller.go]: done

File: pkg/apis/pravega/v1alpha1/status.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/apis/pravega/v1alpha1/status.go]: fixed

File: pkg/controller/pravega/pravega_segmentstore.go (hunk 9 above)
Comment (Tristan1900) [reply pkg/controller/pravega/pravega_segmentstore.go]: done

File: pkg/controller/pravegacluster/upgrade.go [hunk 10]
```diff
@@ -378,3 +465,21 @@ func (r *ReconcilePravegaCluster) getPodsWithVersion(sts *appsv1.StatefulSet, ve
...
+		parsedTime, _ := time.Parse(time.RFC3339, lastCondition.LastUpdateTime)
+		if time.Now().After(parsedTime.Add(time.Duration(10 * time.Minute))) {
+			// timeout
+			return fmt.Errorf("progress deadline exceeded")
+		}
+		// it hasn't reached timeout
+		return nil
+	}
+	// progress has been made, update the status to the latest. This will also set the transition timestamp to now
+	p.Status.SetUpgradingConditionTrue(reason, string(updatedReplicas))
```
Comment (pbelgundi) [inline pkg/controller/pravegacluster/upgrade.go]: Updation of "Upgrading" condition should be inside 'else' block
