### PR TITLE
Issue 91: Pravega metadata cleanup

### LINKED ISSUE #9: Cleanup Zookeeper MetaData on PravegaCluster Delete
When deleting a PravegaCluster the Kubernetes resources are removed but the metadata for the cluster remains in Zookeeper.  This should be removed in order to clean everything up as well as stop it interfering if a cluster with the same name is recreated.

### LINKED ISSUE #91: `WRONG_HOST` error when redeploying a Pravega cluster
### Problem description

When a `PravegaCluster` is destroyed (including PVC) and recreated, a client is unable to communicate with Pravega because the wire protocols returns a `WRONG_HOST` error.

Client error log:
```
root@osboxes:~/pravega-benchmark# ./pravega-benchmark/bin/pravega-benchmark --controller tcp://35.224.63.65:9090 --stream deena -producers 1 --writeonly false --randomkey true --size 100 -eventspersec 3000 --runtime 120                                                       
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 35.224.63.65:9090
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 35.224.63.65:9090
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=9068382028951886715] Tagging client request (createScope-Scope).
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/35.224.63.65:9090], attrs={}]]
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=9068382028951886715] Scope already exists: Scope
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: Scope/deena with configuration: StreamConfiguration(scope=Scope, streamName=deena, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null)
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=7124903224377586204] Tagging client request (createStream-Scope-deena).
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=7124903224377586204] Stream already exists: deena
[pool-1-thread-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/35.224.63.65:9090], attrs={}]]
Current segments of the stream: deena = 1
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ClientFactoryImpl - Creating writer for stream: deena with configuration: EventWriterConfig(initalBackoffMillis=1, maxBackoffMillis=20000, retryAttempts=10, backoffMultiple=10, transactionTimeoutTime=29999)
[main] INFO io.pravega.client.stream.impl.SegmentSelector - Refreshing segments for stream StreamImpl(scope=Scope, streamName=deena)
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment Scope/deena/0.#epoch.0, writerID: 47400b05-b22a-4e46-a11d-95567624fabb
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=35.226.135.109, port=12345) for Scope/deena/0.#epoch.0, writerID: 47400b05-b22a-4e46-a11d-95567624fabb
[epollEventLoopGroup-5-1] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x8bde197e]) 
[epollEventLoopGroup-5-1] INFO io.pravega.shared.protocol.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=6, lowVersion=5)
[epollEventLoopGroup-5-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Failing connection for writer 47400b05-b22a-4e46-a11d-95567624fabb with exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=)
[epollEventLoopGroup-5-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=) for connection io.pravega.client.netty.impl.ClientConnectionInboundHandler@16c96abe on writer 47400b05-b22a-4e46-a11d-95567624fabb. SetupCompleted: false, Closed: false
[epollEventLoopGroup-5-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/deena/0.#epoch.0 on writer 47400b05-b22a-4e46-a11d-95567624fabb failed due to: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=)
[epollEventLoopGroup-5-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - 47400b05-b22a-4e46-a11d-95567624fabb Failed to connect: 
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:874)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.failConnection(SegmentOutputStreamImpl.java:202)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.access$700(SegmentOutputStreamImpl.java:94)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.failConnection(SegmentOutputStreamImpl.java:514)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.access$500(SegmentOutputStreamImpl.java:70)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.wrongHost(SegmentOutputStreamImpl.java:291)
        at io.pravega.shared.protocol.netty.WireCommands$WrongHost.process(WireCommands.java:118)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelRead(ClientConnectionInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=)
        ... 32 more
```

This issue needs to be further investigated, but it seems that remnants from the old Pravega cluster stored in ZooKeeper are conflicting with new clusters if they are given the same name. 

### Suggestions for an improvement

The operator should capture the "destroy" event and execute a clean up procedure that would eliminate any cluster-related data from ZooKeeper.

### Workaround

When destroying a Pravega cluster, also destroy the ZooKeeper cluster and volume claims. E.g. if your ZooKeeper cluster is called `zk` and you have 3 instances:

```
kubectl delete zk zk
kubectl delete pvc data-zk-0
kubectl delete pvc data-zk-1
kubectl delete pvc data-zk-2
```

Then, recreate the ZooKeeper cluster and the Pravega cluster.

### LINKED ISSUE #120: Make Pravega operator tests running in sequence
### Problem description
Master build failed because tests are running randomly. We need to make sure that tests are running in sequence because some of the Pravega operator issues are not fixed. 
### Problem location
Tests
### Suggestions for an improvement
Make go map iteration is in sequence.

### PR DESCRIPTION
**Pull request by Tristan1900**
## Change log description
- Leverage the k8s finalizer to notify Pravega operator before Pravega object is deleted
- Run cleanup routine right after all Pravega cluster pods are terminated
- Make tests run regardless of the order of execution

## Purpose of the change

Fix #91 
Fix #9
Fix #120 

## How to test the change

Checkout to source branch, follow the instructions in the README.md to deploy a Pravega Cluster.

Use port forward to forward a zookeeper node to localhost for testing

```

$kubectl port-forward [zk-node] 2181:2181

```

Install [zk-shell](https://github.com/rgs1/zk_shell) to log into zookeeper to see the changes.

You can use `ls` or `tree` command in zk-shell to examine znodes.

After Pravega Cluster is created, there are two znodes in the root.

```
$zk-shell localhost 2181
(CONNECTED [localhost,2181]) /> ls
pravega
zookeeper
```
The /pravega is used by Pravega Cluster, the /zookeeper is used by zookeeper itself. 

Delete the Pravega Cluster
```
$kubectl delete -f pravega.yaml
```
Check the znode again
```
(CONNECTED [localhost,2181]) /> ls
zookeeper
```
We can see that the /pravega is deleted after Pravega Cluster resource is deleted.

Signed-off-by: wenqi Wenqi.Mou@emc.com

### CODE REVIEW

**Comment by Tristan1900** [comment]
Please ignore diff in /vendor directory. Those are just dependencies.

**Comment by adrianmo** [comment]
[Operator: Zookeeper metadata cleanup](https://trello.com/c/ZTjUsGw8/64-operator-zookeeper-metadata-cleanup)

File: pkg/controller/pravegacluster/pravegacluster_finalizer.go [hunk 1]
```diff
@@ -0,0 +1,165 @@
...
+	if err != nil {
+		return fmt.Errorf("failed to get REST config from kube config: %v", err)
+	}
+
+	coreclient, err := corev1client.NewForConfig(restconfig)
+	if err != nil {
+		return fmt.Errorf("failed to create client from REST config: %v", err)
+	}
+
+	req := coreclient.RESTClient().
```
Comment (adrianmo) [inline pkg/controller/pravegacluster/pravegacluster_finalizer.go]: Let's explore the use of a Zookeeper Go library and use the Service address instead of `exec` into one of the nodes.

File: pkg/controller/pravegacluster/pravegacluster_finalizer.go [hunk 2]
```diff
@@ -0,0 +1,165 @@
...
+		Post().
+		Namespace(zkNode.Namespace).
+		Resource("pods").
+		Name(zkNode.Name).
+		SubResource("exec").
+		VersionedParams(&corev1.PodExecOptions{
+			Container: zkNode.Spec.Containers[0].Name,
+			Command:   []string{"./bin/zkCli.sh", "deleteall", "/pravega"},
```
Comment (adrianmo) [inline pkg/controller/pravegacluster/pravegacluster_finalizer.go]: You should delete the cluster znode (`/pravega/<CLUSTER_NAME>`), not the entire `/pravega`.

Reference:
- https://github.com/pravega/pravega/blob/master/docker/bookkeeper/entrypoint.sh#L68
- https://github.com/pravega/pravega-operator/blob/master/pkg/controller/pravega/bookie.go#L154

File: pkg/controller/pravegacluster/pravegacluster_finalizer.go [hunk 3]
```diff
@@ -0,0 +1,165 @@
...
+		Stderr: os.Stderr,
+		Tty:    true,
+	})
+	if err != nil {
+		return fmt.Errorf("zookeeper is still in use, wait and retry: %v", err)
+	}
+	return nil
+}
+
+func (r *ReconcilePravegaCluster) cleanUpZkUser(p *pravegav1alpha1.PravegaCluster) (err error) {
```
Comment (adrianmo) [inline pkg/controller/pravegacluster/pravegacluster_finalizer.go]: Let's try to find another way of deleting Znodes that does not involve deleting these resources manually. Their lifecycle should be controller by the operator framework instead.

File: pkg/controller/pravegacluster/pravegacluster_finalizer.go (hunk 1 above)
Comment (Tristan1900) [reply pkg/controller/pravegacluster/pravegacluster_finalizer.go]: After researching, I cannot find a zk client that can delete znode recursively. The only way to delete all is to use zkCli.sh, which needs to log in one of the nodes. If we want to use Go library, we will need to write a BFS to delete znode one by one and I suppose that will cause a lot of network traffics. What do you think?

Comment (Tristan1900) [reply pkg/controller/pravegacluster/pravegacluster_finalizer.go]: I am using [go-zookeeper](https://github.com/samuel/go-zookeeper) now

File: pkg/controller/pravegacluster/pravegacluster_finalizer.go (hunk 2 above)
Comment (Tristan1900) [reply pkg/controller/pravegacluster/pravegacluster_finalizer.go]: Got it.

File: pkg/controller/pravegacluster/pravegacluster_finalizer.go (hunk 3 above)
Comment (Tristan1900) [reply pkg/controller/pravegacluster/pravegacluster_finalizer.go]: Sounds reasonable.

**Comment by Tristan1900** [comment]
This PR is ready for second review now.

File: pkg/test/e2e/e2eutil/spec_util.go [hunk 4]
```diff
@@ -76,3 +77,26 @@ func NewTestWriteReadJob(namespace string, controllerUri string) *batchv1.Job {
 		controllerUri, controllerUri)
 	return newTestJob(namespace, command)
 }
+
+func GetTier2(namespace string) *corev1.PersistentVolumeClaim {
```
Comment (adrianmo) [inline pkg/test/e2e/e2eutil/spec_util.go]: The function name seems wrong to me. `NewTier2` probably sounds better and is consistent with the rest of the funcs.

File: pkg/util/pravegacluster.go [hunk 5]
```diff
@@ -108,3 +115,48 @@ func Min(x, y int32) int32 {
 	}
 	return x
 }
+
+func ListSubTreeBFS(conn *zk.Conn, root string) (*list.List, error) {
```
Comment (adrianmo) [inline pkg/util/pravegacluster.go]: This function should be moved to some other place. Maybe you can create a `zookeeper_util.go` file.

File: Makefile [hunk 6]
```diff
@@ -39,7 +40,15 @@ test-unit:
 	go test $$(go list ./... | grep -v /vendor/ | grep -v /test/e2e )
 
 test-e2e:
-	operator-sdk test local ./test/e2e --go-test-flags -v --namespace default --up-local
+	sed "s@REPLACE_IMAGE@$(TEST_IMAGE)@g" -i deploy/operator.yaml
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply Makefile]: Sure. The reason is when we use local flag, the operator is running in the local environment. If I need to access zk service which specified in the Pravega yaml file as "zk-client:2181" in default, I will need the operator deployed in the k8s environment. "Test cluster" command will deploy the image for us in k8s and that needs those kubectl commands to run first. [Ref](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md#cluster)

File: deploy/operator.yaml [hunk 7]
```diff
@@ -15,7 +15,7 @@ spec:
       serviceAccountName: pravega-operator
       containers:
         - name: pravega-operator
-          image: pravega/pravega-operator:latest
+          image: REPLACE_IMAGE
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply deploy/operator.yaml]: Got it.

File: pkg/controller/pravegacluster/pravegacluster_controller.go [hunk 8]
```diff
@@ -323,3 +332,86 @@ func (r *ReconcilePravegaCluster) syncControllerSize(p *pravegav1alpha1.PravegaC
...
+		return nil
+	}
+}
+
+func (r *ReconcilePravegaCluster) cleanUpZookeeperMeta(p *pravegav1alpha1.PravegaCluster) (err error) {
+	listOptions := &client.ListOptions{
+		LabelSelector: labels.SelectorFromSet(util.LabelsForPravegaCluster(p)),
+	}
+
+	err = wait.Poll(e2eutil.RetryInterval, 2*time.Minute, func() (done bool, err error) {
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/controller/pravegacluster/pravegacluster_controller.go]: Ok I will try.

File: pkg/controller/pravegacluster/pravegacluster_controller.go [hunk 9]
```diff
@@ -323,3 +332,86 @@ func (r *ReconcilePravegaCluster) syncControllerSize(p *pravegav1alpha1.PravegaC
...
+
+	root := fmt.Sprintf("/%s/%s", util.PravegaPath, p.Name)
+	exist, _, err := conn.Exists(root)
+	if err != nil {
+		return fmt.Errorf("failed to check if zookeeper path exists: %v", err)
+	}
+
+	if exist {
+		// Construct BFS tree to delete all znodes recursively
+		tree, err := util.ListSubTreeBFS(conn, root)
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/controller/pravegacluster/pravegacluster_controller.go]: Got it.

File: pkg/test/e2e/e2eutil/spec_util.go (hunk 4 above)
Comment (Tristan1900) [reply pkg/test/e2e/e2eutil/spec_util.go]: Yeah... I was trying to make it consistent, but this yaml is the Go version of /test/e2e/resource/tier2.yaml. I am not sure if New will make it confusing because what the test code does it to get that deployed tier2 and delete it. If you think New is better I am cool with it.

File: pkg/util/pravegacluster.go (hunk 5 above)
Comment (Tristan1900) [reply pkg/util/pravegacluster.go]: Sounds good

File: pkg/util/zookeeper_util.go [hunk 10]
```diff
@@ -0,0 +1,120 @@
...
+)
+
+const (
+	// Set in https://github.com/pravega/pravega/blob/master/docker/bookkeeper/entrypoint.sh#L21
+	PravegaPath = "pravega"
+	ZkFinalizer = "cleanUpZookeeper"
+)
+
+// Wait for pods in cluster to be terminated
+func WaitForClusterToTerminate(kubeClient client.Client, p *v1alpha1.PravegaCluster) (err error) {
```
Comment (adrianmo) [inline pkg/util/zookeeper_util.go]: This function fits better in `k8sutil.go` as it does not contain any ZK logic.

File: test/e2e/basic_test.go [hunk 11]
```diff
@@ -50,15 +50,92 @@ func testCreateDefaultCluster(t *testing.T) {
...
 
-	err = pravega_e2eutil.WaitForClusterToTerminate(t, f, ctx, pravega)
+	err = pravega_e2eutil.WaitForClusterToTerminate(t, f, pravega)
+	if err != nil {
+		t.Fatal(err)
+	}
+}
+
+// Test restart Pravega cluster with the same name(issue 91)
+func testRestartDefaultCluster(t *testing.T) {
```
Comment (adrianmo) [inline test/e2e/basic_test.go]: I think the word "recreate" better describes this test case than "restart". IMO "restart" implies using the exact same cluster object, which is not the case.

File: pkg/test/e2e/e2eutil/spec_util.go (hunk 4 above)
Comment (adrianmo) [reply pkg/test/e2e/e2eutil/spec_util.go]: I understand your concern, but since it's creating a new spec, `NewTier2` seems a better option.

File: Makefile (hunk 6 above)
[the remark this answers is not in the document]
Comment (adrianmo) [reply Makefile]: According to the documentation, that's not true. `test local` runs the tests locally, but the operator runs in the cluster. What makes the operator run locally is the [`--up-local`](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md#up-local-flag) flag. Therefore, I don't see the need to use the `test cluster` and also run the tests in the cluster, adding those unnecessary preparation steps.

File: pkg/test/e2e/e2eutil/pravegacluster_util.go [hunk 12]
```diff
@@ -63,17 +64,17 @@ func DeleteCluster(t *testing.T, f *framework.Framework, ctx *framework.TestCtx,
...
+		if condition.Type == corev1.PodReady && condition.Status == corev1.ConditionTrue {
 			return true
 		}
 	}
 	return false
 }
 
 // WaitForClusterToStart will wait until all cluster pods are ready
-func WaitForClusterToStart(t *testing.T, f *framework.Framework, ctx *framework.TestCtx, p *api.PravegaCluster, size int) error {
+func WaitForClusterToStart(t *testing.T, f *framework.Framework, p *api.PravegaCluster, size int) error {
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/test/e2e/e2eutil/pravegacluster_util.go]: I noticed that ctx is not used in the function.

File: pkg/util/zookeeper_util.go (hunk 10 above)
Comment (Tristan1900) [reply pkg/util/zookeeper_util.go]: Got it

File: test/e2e/basic_test.go (hunk 11 above)
Comment (Tristan1900) [reply test/e2e/basic_test.go]: You are right

File: pkg/test/e2e/e2eutil/pravegacluster_util.go [hunk 13]
```diff
@@ -110,7 +111,7 @@ func WaitForClusterToStart(t *testing.T, f *framework.Framework, ctx *framework.
 }
 
 // WaitForClusterToTerminate will wait until all cluster pods are terminated
-func WaitForClusterToTerminate(t *testing.T, f *framework.Framework, ctx *framework.TestCtx, p *api.PravegaCluster) error {
+func WaitForClusterToTerminate(t *testing.T, f *framework.Framework, p *api.PravegaCluster) error {
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/test/e2e/e2eutil/pravegacluster_util.go]: I'm afraid that I am not able to find a way for code reuse of WaitforClusterToTerminate. In the test code, it is using framwork.client or kubernetes package to communicate with k8s. But in operator reconcile loop, it is using controller-runtime client to talk to k8s. Any suggestions on how to reuse code?

File: pkg/test/e2e/e2eutil/spec_util.go (hunk 4 above)
Comment (Tristan1900) [reply pkg/test/e2e/e2eutil/spec_util.go]: Done

File: Makefile (hunk 6 above)
[the remark this answers is not in the document]
Comment (Tristan1900) [reply Makefile]: You are right!

**Comment by adrianmo** [comment]
@fpj can you please review the PR? Thanks.
