### PR TITLE
Issue 186: Detecting error/failure during upgrade

### LINKED ISSUE #186: Upgrade process fails to detect the error/failure and fails to set the `Error` status to `True`
**Upgrade process waits indefinitely for the failed pod to recover and not updating the `Error` and `upgrading` status appropriately**

When I tried to simulate upgrade failure scenario by upgrading Pravega cluster version from `0.5.0-2222.8ba543`1 to `0.5.0-2222` (Here 0.5.0-2222 docker image is not existing), upgrade process failing to detect the `ImagePullBackOff`  Error on the `Bookie-0` pod.

I was expecting the upgrade process will detect the failure/timeout and update the status of `Error` to `True` and `upgrading` status to `false`. But the upgrade process is waiting indefinitely (tested for more than a day) for `Bookie-0` pod to recover and not updating the status of upgrade failure.

**kubectl describe PravegaCluster output**
```
Status:
  Conditions:
    Last Transition Time:  2019-05-15T07:57:10Z
    Last Update Time:      2019-05-15T07:57:10Z
    Status:                True
    Type:                  Upgrading
    Last Transition Time:  2019-05-15T07:58:28Z
    Last Update Time:      2019-05-15T07:58:28Z
    Status:                False
    Type:                  PodsReady
    Status:                False
    Type:                  Error
  Current Replicas:        9
  Current Version:         0.5.0-2222.8ba5431
  Members:
    Ready:
      pravega-bookie-1
      pravega-bookie-2
      pravega-bookie-3
      pravega-pravega-controller-7f89bff94d-sct8n
      pravega-pravega-controller-7f89bff94d-wkdnk
      pravega-pravega-segmentstore-0
      pravega-pravega-segmentstore-1
      pravega-pravega-segmentstore-2
    Unready:
      pravega-bookie-0
  Ready Replicas:  8
  Replicas:        9
  Target Version:  0.5.0-2222
Events:            <none>
```
```
# kubectl get pravegacluster
NAME      VERSION              DESIRED VERSION   DESIRED MEMBERS   READY MEMBERS   AGE
pravega   0.5.0-2222.8ba5431                     9                 8               3d
```
**Pod status**
```
[root@master May-17]# kubectl get po  --all-namespaces
NAMESPACE     NAME                                                 READY   STATUS             RESTARTS   AGE
default       boiling-ragdoll-pravega-operator-7695d64cf-rvzdf     1/1     Running            0          4d
default       pravega-benchmark                                    1/1     Running            0          3d3h
default       pravega-bookie-0                                     0/1     ImagePullBackOff   0          2d5h
default       pravega-bookie-1                                     1/1     Running            0          3d1h
default       pravega-bookie-2                                     1/1     Running            0          3d1h
default       pravega-bookie-3                                     1/1     Running            0          3d1h
default       pravega-pravega-controller-7f89bff94d-sct8n          1/1     Running            0          3d1h
default       pravega-pravega-controller-7f89bff94d-wkdnk          1/1     Running            0          3d1h
default       pravega-pravega-segmentstore-0                       1/1     Running            0          3d1h
default       pravega-pravega-segmentstore-1                       1/1     Running            0          3d1h
default       pravega-pravega-segmentstore-2                       1/1     Running            0          3d1h
default       pravega-zk-0                                         1/1     Running            0          3d23h
default       pravega-zk-1                                         1/1     Running            0          3d23h
default       pravega-zk-2                                         1/1     Running            0          3d23h
default       shaka-zulu-nfs-client-provisioner-59d7f8f84c-tvh7w   1/1     Running            0          3d23h
default       zookeeper-operator-685bfcbbc5-7r48t                  1/1     Running            0          3d23h
```

**Logs from Pravega-operator:**
```
time="2019-05-15T07:57:10Z" level=info msg="syncing cluster version from 0.5.0-2222.8ba5431 to 0.5.0-2222"
ng statefulset (pravega-bookie) template image to 'devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2222'"
time="2019-05-15T07:57:27Z" level=info msg="Reconciling PravegaCluster default/prtime="2019-05-15T07:57:10Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:57:10Z" level=info msg="updating statefulset (pravega-bookie) template image to 'devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2222'"
time="2019-05-15T07:57:27Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:57:27Z" level=info msg="statefulset (pravega-bookie) status: 0 updated, 4 ready, 4 target"
time="2019-05-15T07:57:27Z" level=info msg="upgrading pod: pravega-bookie-0"
time="2019-05-15T07:57:57Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:57:58Z" level=info msg="statefulset (pravega-bookie) status: 0 updated, 4 ready, 4 target"
time="2019-05-15T07:57:58Z" level=info msg="upgrading pod: pravega-bookie-0"
time="2019-05-15T07:58:28Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:58:28Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:58:28Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:58:28Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:58:58Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:58:58Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:59:28Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-15T07:59:28Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-15T07:59:58Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
..............
...............
time="2019-05-17T12:47:59Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:47:59Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:48:29Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:48:29Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:48:59Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:48:59Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:49:29Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:49:30Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:50:00Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:50:00Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:50:30Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:50:30Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:51:00Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:51:00Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
time="2019-05-17T12:51:30Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-05-17T12:51:30Z" level=info msg="statefulset (pravega-bookie) status: 1 updated, 3 ready, 4 target"
 ```

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
The upgrade process waits indefinitely for the failed pod to recover and does not update the `Error` and `Upgrading` status appropriately.

**kubectl describe PravegaCluster output**
```
Status:
  Conditions:
    Last Transition Time:  2019-05-15T07:57:10Z
    Last Update Time:      2019-05-15T07:57:10Z
    Status:                True
    Type:                  Upgrading
    Last Transition Time:  2019-05-15T07:58:28Z
    Last Update Time:      2019-05-15T07:58:28Z
    Status:                False
    Type:                  PodsReady
    Status:                False
    Type:                  Error
  Current Replicas:        5
  Current Version:         0.5.0-2222.8ba5431
  Members:
    Ready:
      bar-pravega-bookie-1
      bar-pravega-bookie-2
      bar-pravega-pravega-controller-7d6cbd8554-b9pdv
      bar-pravega-pravega-segmentstore-0
    Unready:
      bar-pravega-bookie-0
  Ready Replicas:  4
  Replicas:        5
  Target Version:  0.5.0-2222
Events:            <none>
```

### Purpose of the change
Fixes #186 

### What the code does
The code detects the scenario where a pod upgrade fails due to an `ImagePullBackOff` error and appropriately updates the  `Error` and `Upgrading` status of the PravegaCluster.

### How to verify it
To reproduce the issue tried upgrading a sample Pravega Cluster from version 0.5.0-2222.8ba5431 to version 0.5.0-2222 (which is an invalid version as the corresponding docker image does not exist). The upgrade process was unable to detect the failure and waited indefinitely as mentioned in the issue.

Created a new operator image with the fix and confirmed that the error reported in the issue is not noticed after the fix, i.e. the `Error` and `Upgrading` status of the PravegaCluster were updated appropriately. The following result is obtained after the fix has been applied :-

**kubectl describe PravegaCluster output**
```
Status:
  Conditions:
    Last Transition Time:  2019-08-07T12:59:12Z
    Last Update Time:      2019-08-07T12:59:12Z
    Status:                False
    Type:                  Upgrading
    Last Transition Time:  2019-08-07T12:58:42Z
    Last Update Time:      2019-08-07T12:58:42Z
    Status:                False
    Type:                  PodsReady
    Last Transition Time:  2019-08-07T12:59:12Z
    Last Update Time:      2019-08-07T12:59:12Z
    Message:               failed to sync bookkeeper version. pod bar-pravega-bookie-0 update failed because of ImagePullBackOff
    Reason:                UpgradeFailed
    Status:                True
    Type:                  Error
  Current Replicas:        5
  Current Version:         0.5.0-2222.8ba5431
  Members:
    Ready:
      bar-pravega-bookie-1
      bar-pravega-bookie-2
      bar-pravega-pravega-controller-7d6cbd8554-b9pdv
      bar-pravega-pravega-segmentstore-0
    Unready:
      bar-pravega-bookie-0
  Ready Replicas:  4
  Replicas:        5
Events:            <none>

```

### CODE REVIEW

File: pkg/controller/pravegacluster/upgrade.go [hunk 1]
```diff
@@ -315,6 +315,9 @@ func (r *ReconcilePravegaCluster) checkUpdatedPods(sts *appsv1.StatefulSet, vers
 
 		if !util.IsPodReady(pod) {
 			// At least one updated pod is still not ready
+			if pod.Status.ContainerStatuses[0].State.Waiting.Reason == "ImagePullBackOff" {
```
Comment (pbelgundi) [inline pkg/controller/pravegacluster/upgrade.go]: This solves only the "ImagePullBackOff" reason for update failure. There could be more reasons why an update could fail. Ideally we want to capture any unrecoverable upgrade failure and report it.
What can we do to solve this more generically?

Please make sure this is tested for positive and negative test case scenarios.
Please add unit tests to cover these.

File: pkg/controller/pravegacluster/upgrade.go [hunk 2]
```diff
@@ -315,6 +315,9 @@ func (r *ReconcilePravegaCluster) checkUpdatedPods(sts *appsv1.StatefulSet, vers
...
+				return false, fmt.Errorf("pod %s update failed because of ImagePullBackOff", pod.Name)
```
Comment (pbelgundi) [inline pkg/controller/pravegacluster/upgrade.go]: It would be good to print the reason using `fmt.Errorf("pod %s update failed because of %s", pod.Name, pod.Status.ContainerStatuses[0].State.Waiting.Reason)`

File: pkg/controller/pravegacluster/upgrade.go (hunk 1 above)
Comment (pbelgundi) [inline pkg/controller/pravegacluster/upgrade.go]: If the container starts correctly(without any errors), there would not be any value like `pod.Status.ContainerStatuses[0].State.Waiting` and this code would throw an exception.
It would be good to have a check like:
` if pod.Status.ContainerStatuses[0].State == ContainerState.Waiting 
 && pod.Status.ContainerStatuses[0].State.Reason == ImagePullBackOff`

File: pkg/controller/pravegacluster/upgrade.go (hunk 2 above)
Comment (SrishT) [reply pkg/controller/pravegacluster/upgrade.go]: Included this change

File: pkg/controller/pravegacluster/upgrade.go (hunk 1 above)
Comment (SrishT) [reply pkg/controller/pravegacluster/upgrade.go]: If the container starts correctly, `pod.Status.ContainerStatuses[0].State.Waiting` is set to nil. Added the following check to the code to avoid such exceptions :
`if pod.Status.ContainerStatuses[0].State.Waiting != nil && pod.Status.ContainerStatuses[0].State.Waiting.Reason == "ImagePullBackOff"`

Comment (SrishT) [reply pkg/controller/pravegacluster/upgrade.go]: In case upgrade fails due to a `ContainerState` terminating with a non-zero exit status, Kubernetes tries to bring up the pod again by restarting the pod. After a certain number of retries it detects the failure and the process terminates with the message `"error syncing cluster version, need manual intervention. failed to sync bookkeeper version. pod bar-pravega-bookie-0 is restarting"`

The `Error` Status is also appropriately updated, as can be seen from the following output

**kubectl describe PravegaCluster**
```
Status:
  Conditions:
    Last Transition Time:  2019-08-19T06:02:15Z
    Last Update Time:      2019-08-19T06:02:15Z
    Status:                False
    Type:                  Upgrading
    Last Transition Time:  2019-08-19T06:01:43Z
    Last Update Time:      2019-08-19T06:01:43Z
    Status:                False
    Type:                  PodsReady
    Last Transition Time:  2019-08-19T06:02:15Z
    Last Update Time:      2019-08-19T06:02:15Z
    Message:               failed to sync bookkeeper version. pod bar-pravega-bookie-0 is restarting
    Reason:                UpgradeFailed
    Status:                True
    Type:                  Error
  Current Replicas:        5
  Current Version:         0.5.0-2222.8ba5431
```

File: pkg/controller/pravegacluster/upgrade.go (hunk 2 above)
Comment (pbelgundi) [reply pkg/controller/pravegacluster/upgrade.go]: Ok
