### PR TITLE
Issue371: Fixing endtoend tests of pravega-operator

### LINKED ISSUE #371: Fixing endtoend tests of pravega-operator
### Description

End to end tests of pravega-operator are failing

### Importance

Must have

### Location

test/e2e

### Suggestions for an improvement

Improve feature coverage of tests

### PR DESCRIPTION
**Pull request by anishakj**
Signed-off-by: anisha.kj <anisha.kj@dell.com>

### Change log description
Fixed the endtoend tests, as it got broken with controller-runtime update

### Purpose of the change

Fixes #371

### What the code does
Upgraded operator-sdk version to v0.17.0
Modified tests as the CRD version changed to v1beta1
### How to verify it

Verified by running endtoend tests

### CODE REVIEW

File: test/e2e/upgrade_test.go [hunk 1]
```diff
@@ -41,10 +41,8 @@ func testUpgradeCluster(t *testing.T) {
 	initialVersion := "0.5.0-1"
 	upgradeVersion := "0.5.0-2"
 	cluster.Spec.Version = initialVersion
-	cluster.Spec.Pravega.Image = &api.PravegaImageSpec{
-		ImageSpec: api.ImageSpec{
-			Repository: "adrianmo/pravega",
-		},
+	cluster.Spec.Pravega.Image = &api.ImageSpec{
+		Repository: "adrianmo/pravega",
```
Comment (pbelgundi) [inline test/e2e/upgrade_test.go:45]: Lets remove dependency on this private repository: "adrianmo"

Comment (anishakj) [reply test/e2e/upgrade_test.go]: Changed
