### PR TITLE
Issue 491: Handling config key name changes

### LINKED ISSUE #491: Pravega webhook fails upgrade even when the name of the container count property is modified as per the new naming convention
### Description
Pravega webhook fails upgrade even when just the name of the container count property is modified as per the new naming convention.

### Importance
must have

### Location
pkg/apis/pravega/v1beta1/pravegacluster_types.go

### Suggestions for an improvement
While the value of this property should never be allowed to change, the name of this property needs to change when upgrading pravega version to above 0.9.0

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
Pravega webhook fails upgrade even when just the name of the configuration keys is modified as per the new naming convention (ref. https://github.com/pravega/pravega/pull/4713)

### Purpose of the change
Fixes #491 

### How to verify it
Upgrade pravega from version 0.7.0 to 0.8.0 and along with it also modify the name of the pravega option name from `controller.containerCount` to `controller.container.count` without modifying its value. The upgrade should be allowed and you should not see the following error message
```
cannot patch "nautilus" with kind PravegaCluster: admission webhook "pravegawebhook.pravega.io" denied the request: controller.container.count should not be changed
```

### CODE REVIEW

File: pkg/apis/pravega/v1beta1/pravegacluster_types.go [hunk 1]
```diff
@@ -1065,8 +1069,10 @@ func (p *PravegaCluster) validateConfigMap() error {
 	}
 	if val, ok := p.Spec.Pravega.Options["bookkeeper.ledger.path"]; ok {
 		checkstring := fmt.Sprintf("-Dbookkeeper.ledger.path=%v", val)
-		eq := strings.Contains(configmap.Data["JAVA_OPTS"], checkstring)
-		if !eq {
+		eq_new := strings.Contains(configmap.Data["JAVA_OPTS"], checkstring)
```
Comment (Prabhaker24) [inline pkg/apis/pravega/v1beta1/pravegacluster_types.go:1072]: In place of contains let's check if the configmap.Data["JAVA_OPTS"] is equal to the checkstring or not to avoid any false positives.
Please change this at all other places too.

**Review by Prabhaker24 — CHANGES_REQUESTED** [review]

File: pkg/apis/pravega/v1beta1/pravegacluster_types.go (hunk 1 above)
Comment (SrishT) [reply pkg/apis/pravega/v1beta1/pravegacluster_types.go:1072]: We cannot use the equals check here since this particular option is just one of the options within the list of java options for pravega.

Comment (Prabhaker24) [reply pkg/apis/pravega/v1beta1/pravegacluster_types.go:1072]: what I meant is let's think of a logic where we should check if specific option field value is equal to the changed value or not.
for eg think of a case where a user tries to change ledger path from **ledgers/temp1 to ledgers**   this will pass our check even though the ledger path is changed.

**Review by Prabhaker24 — CHANGES_REQUESTED** [review]

**Review by Prabhaker24 — APPROVED** [review]
LGTM

**Review by anishakj — APPROVED** [review]
LGTM
