### PR TITLE
Issue 354: Segment store pods are not coming up with external access

### LINKED ISSUE #354: Segment store pods are not coming up with external access
### Description

Segment store pods are entering in `Crash Loop Back` state with `05.0-rc0` operator with external access eabled
### Importance

Must have
### Location

pkg/controller/pravega/pravega_segmentstore.go

### Suggestions for an improvement

Operator should be able to bring up segment store pods

### PR DESCRIPTION
**Pull request by anishakj**
Signed-off-by: anisha.kj <anisha.kj@dell.com>

### Change log description

In pravega operator `0.5`, we are creating STS with different name that  in turn changes pod name. Due to that init script of pravega is failing as  it assumes pod name is same service name.  And segment containers are not coming up.POD_NAME is passed as env variable from operator to pravega init script

### Purpose of the change

Fixes #354

### What the code does
From 0.7 pravega onwards, pod name and external service names were different with 0.5 operator.
Changed external service name to pod name, so that external service name and pod name will have the same name in every pravega version. Also while doing upgrade from 0.6 to 0.7, delete the external services and create services with same name of pravega-0.7 segment store pods.

### How to verify it
Tested the below scenarios with external connectivity
1. Able to deploy pravega 0.7 with operator
2. Tried upgarde from 0.6 to 0.7 while IO work load is running. IO has stalled for a minute, while it is upgrading but it is resuming fine
3. Tried Rollback by making the upgrade from 0.6 to 0.7 fail

All the above scenarios have passed

### CODE REVIEW

File: pkg/controller/pravegacluster/upgrade.go [hunk 1]
```diff
@@ -444,12 +444,29 @@ func (r *ReconcilePravegaCluster) syncSegmentStoreVersionTo07(p *pravegav1alpha1
 	//this check is to see if the newsts is present or not if it's not present it will be created here
 	if err != nil {
 		if errors.IsNotFound(err) {
+			if p.Spec.ExternalAccess.Enabled {
```
Comment (pbelgundi) [inline pkg/controller/pravegacluster/upgrade.go:447]: It would be good to create the services after the new STS is created. Just move this if block  to ln 469

Comment (pbelgundi) [reply pkg/controller/pravegacluster/upgrade.go:447]: Encapsulate all the code inside the if block in a method and invoke the same here, instead of adding code inline.

File: pkg/controller/pravegacluster/upgrade.go [hunk 2]
```diff
@@ -564,6 +581,30 @@ func (r *ReconcilePravegaCluster) transitionToNewSTS(p *pravegav1alpha1.PravegaC
 	}
 	//this is to check if all the new ss pods have comeup before deleteing the old sts
 	if newsts.Status.ReadyReplicas == p.Spec.Pravega.SegmentStoreReplicas {
+		if p.Spec.ExternalAccess.Enabled {
```
Comment (pbelgundi) [inline pkg/controller/pravegacluster/upgrade.go:584]: Again, Encapsulate all the code inside the if block in a method and invoke the method here... something like ...
`if p.Spec.ExternalAccess.Enabled { deleteExternalServices(. . .) } `

File: pkg/util/pravegacluster.go [hunk 3]
```diff
@@ -116,6 +119,14 @@ func StatefulSetNameForSegmentstoreBelow07(name string) string {
 	return fmt.Sprintf("%s-pravega-segmentstore", name)
 }
 
+func ServiceNameForSegmentStoreBelow07(name string, index int32) string {
```
Comment (pbelgundi) [inline pkg/util/pravegacluster.go:122]: Do we really need these 2 methods? 
It would be better to have all the name generation logic in **one** place inside method "ServiceNameForSegmentStore" and always invoke this method by passing PravegaCluster object as parameter.

File: pkg/controller/pravegacluster/upgrade.go (hunk 1 above)
Comment (anishakj) [reply pkg/controller/pravegacluster/upgrade.go:479]: > It would be good to create the services after the new STS is created. Just move this if block to ln 469

We wont be able to do that because sts is created with "0" replicas and in pravega.spec.replicas it will set the value., due to that external services wont get created. And we are creating sts in case of external service creation fails.

Comment (anishakj) [reply pkg/controller/pravegacluster/upgrade.go:479]: > Encapsulate all the code inside the if block in a method and invoke the same here, instead of adding code inline.

Done

File: pkg/util/pravegacluster.go (hunk 3 above)
Comment (anishakj) [reply pkg/util/pravegacluster.go]: Done

**Comment by Prabhaker24** [comment]
LGTM
