### PR TITLE
Issue 317: Adding Unit Tests for the module pkg/controller/pravega

### LINKED ISSUE #317: Increase code coverage in the module pkg/controller/pravega to > 85%
### Description
The given module has no test files currently.

### Importance
Low code coverage hinders with robust testing of changes and and does not allow us to fail fast.

### Location
Current statement coverage of the given module : nil

### Suggestions for an improvement
Add tests to cover all possible code paths such that we get code coverage > 85%

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
Adds unit tests to cover all possible code paths in the given module.

### Purpose of the change
Fixes #317 

### What the code does
It increases the code coverage for the module `pkg/controller/pravega` to 96.2%

### How to verify it
The Unit Tests should pass with coverage > 80%

### CODE REVIEW

File: pkg/controller/pravega/pravega_segmentstor_test.go [hunk 1]
```diff
@@ -0,0 +1,408 @@
+/**
```
Comment (pbelgundi) [inline pkg/controller/pravega/pravega_segmentstor_test.go]: Filename should be `pravega_segmentstore_test.go`

Comment (SrishT) [reply pkg/controller/pravega/pravega_segmentstor_test.go]: done
