### PR TITLE
issue:309 fix for webhook check failure for rollback

### LINKED ISSUE #309: Rollback failed with 0.4.3-rc1 operator for 0.6.0-2408.7312399 version
I deployed pravega with following config:
```
bookkeeper: 0.6.0-2408.7312399
pravega:0.6.0-2408.7312399
pravega/pravega-operator:0.4.3-rc1
pravega/zookeeper:0.2.5-rc0
pravega/zookeeper-operator:0.2.5-rc0
```
It deployed successfully.
Then tried to Upgrade to `0.6.1-2419.5ae9098` but in between Upgrade failed after upgrading 2 bookies out of 4 and gave following error message:
```
Error Upgrading from version 0.6.0-2408.7312399 to 0.6.1-2419.5ae9098. failed to sync bookkeeper version. updating statefulset (pravega-bookie) failed due to progress deadline exceeded
```
When I tried to rollback it to `0.6.0-2408.7312399`, it gave me following error message:
```
[root@nile3-vm55 ~]# kubectl edit PravegaCluster
error: pravegaclusters.pravega.pravega.io "pravega" could not be patched: Internal error occurred: admission webhook "pravegawebhook.pravega.io" denied the request: unsupported upgrade from version 0.6.1-2419.5ae9098 to 0.6.0-2408.7312399
You can run `kubectl replace -f /tmp/kubectl-edit-80p3i.yaml` to try this update again.
```
Following is the `describe` for `PravegaCluster` :
```
[root@nile3-vm55 ~]# kubectl describe PravegaCluster
Name:         pravega
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  pravega.pravega.io/v1alpha1
Kind:         PravegaCluster
Metadata:
  Creation Timestamp:  2019-12-06T09:02:18Z
  Finalizers:
    cleanUpZookeeper
  Generation:        3
  Resource Version:  8194105
  Self Link:         /apis/pravega.pravega.io/v1alpha1/namespaces/default/pravegaclusters/pravega
  UID:               1afcdeff-1807-11ea-ad8b-005056b2eab5
Spec:
  Authentication:
    Enabled:  false
  Bookkeeper:
    Auto Recovery:  true
    Bookkeeper JVM Options:
      Extra Opts:
      Gc Logging Opts:
      Gc Opts:
      Memory Opts:
    Image:
      Pull Policy:  Always
      Repository:   devops-repo.isus.emc.com:8116/nautilus/bookkeeper
    Options:
      Disk Usage Lwm Threshold:         0.85
      Disk Usage Threshold:             0.90
      Disk Usage Warn Threshold:        0.85
      Is Force GC Allow When No Space:  true
      Major Compaction Interval:        43200
      Major Compaction Threshold:       0.8
      Minor Compaction Interval:        1800
      Minor Compaction Threshold:       0.4
      Use Host Name As Bookie ID:       true
    Replicas:                           4
    Resources:
      Limits:
        Cpu:     2
        Memory:  6Gi
      Requests:
        Cpu:     1
        Memory:  2Gi
    Storage:
      Index Volume Claim Template:
        Access Modes:
          ReadWriteOnce
        Data Source:  <nil>
        Resources:
          Requests:
            Storage:         30Gi
        Storage Class Name:  standard
      Journal Volume Claim Template:
        Access Modes:
          ReadWriteOnce
        Data Source:  <nil>
        Resources:
          Requests:
            Storage:         200Gi
        Storage Class Name:  standard
      Ledger Volume Claim Template:
        Access Modes:
          ReadWriteOnce
        Data Source:  <nil>
        Resources:
          Requests:
            Storage:         200Gi
        Storage Class Name:  standard
  External Access:
    Enabled:  false
  Pravega:
    Cache Volume Claim Template:
      Access Modes:
        ReadWriteOnce
      Data Source:  <nil>
      Resources:
        Requests:
          Storage:         30Gi
      Storage Class Name:  standard
    Controller Replicas:   2
    Controller Resources:
      Limits:
        Cpu:     2
        Memory:  3Gi
      Requests:
        Cpu:     1
        Memory:  2Gi
    Controller Svc Annotations:
    Controllerjvm Options:
    Debug Logging:  false
    Image:
      Pull Policy:  Always
      Repository:   devops-repo.isus.emc.com:8116/nautilus/pravega
    Options:
      Bookkeeper . Bk Ack Quorum Size:                   3
      Bookkeeper . Bk Write Quorum Size:                 3
      Controller . Container Count:                      32
      Controller . Metrics . Dynamic Cache Size:         100000
      Controller . Metrics . Enable Influx DB Reporter:  true
      Controller . Metrics . Enable Statistics:          true
      Controller . Metrics . Enable Stats D Reporter:    false
      Controller . Metrics . Influx DBURI:               http://172.28.85.2:8086
      Controller . Metrics . Output Frequency Seconds:   10
      Controller . Metrics . Statsd Host:                telegraph.default
      Controller . Metrics . Statsd Port:                8125
      Controller . Retention . Bucket Count:             10
      Controller . Retention . Thread Count:             4
      Controller . Service . Async Task Pool Size:       20
      Hdfs . Block Size:                                 67108864
      Log . Level:                                       INFO
      Metrics . Dynamic Cache Size:                      100000
      Metrics . Enable Influx DB Reporter:               true
      Metrics . Enable Statistics:                       true
      Metrics . Enable Stats D Reporter:                 false
      Metrics . Influx DBURI:                            http://172.28.85.2:8086
      Metrics . Output Frequency Seconds:                10
      Metrics . Statsd Host:                             telegraph.default
      Metrics . Statsd Port:                             8125
      Pravegaservice . Cache Max Size:                   3221225472
      Pravegaservice . Cache Max Time Seconds:           600
      Pravegaservice . Container Count:                  32
      Pravegaservice . Thread Pool Size:                 30
      Rocksdb . Cache Block Size KB:                     32
      Rocksdb . Read Cache Size MB:                      8
      Rocksdb . Write Buffer Size MB:                    64
      Writer . Flush Threshold Bytes:                    67108864
      Writer . Flush Threshold Millis:                   2000
      Writer . Max Flush Size Bytes:                     67108864
      Writer . Min Read Timeout Millis:                  200
    Segment Store JVM Options:
    Segment Store Replicas:  3
    Segment Store Resources:
      Limits:
        Cpu:     4
        Memory:  8Gi
      Requests:
        Cpu:     2
        Memory:  4Gi
    Segment Store Svc Annotations:
    Tier 2:
      Filesystem:
        Persistent Volume Claim:
          Claim Name:  pravega-tier2
  Tls:
    Static:
  Version:        0.6.1-2419.5ae9098
  Zookeeper Uri:  pravega-zk-0.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-1.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-3.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-4.pravega-zk-headless.default.svc.cluster.local:2181
Status:
  Conditions:
    Last Transition Time:  2019-12-06T09:34:28Z
    Last Update Time:      2019-12-06T09:34:28Z
    Status:                False
    Type:                  Upgrading
    Last Transition Time:  2019-12-06T09:24:26Z
    Last Update Time:      2019-12-06T09:24:26Z
    Status:                False
    Type:                  PodsReady
    Last Transition Time:  2019-12-06T09:34:28Z
    Last Update Time:      2019-12-06T09:34:28Z
    Message:               failed to sync bookkeeper version. updating statefulset (pravega-bookie) failed due to progress deadline exceeded
    Reason:                UpgradeFailed
    Status:                True
    Type:                  Error
  Current Replicas:        9
  Current Version:         0.6.0-2408.7312399
  Members:
    Ready:
      pravega-bookie-0
      pravega-bookie-1
      pravega-bookie-3
      pravega-pravega-controller-6cbf86b5f4-57gfd
      pravega-pravega-controller-6cbf86b5f4-x97sw
      pravega-pravega-segmentstore-0
      pravega-pravega-segmentstore-1
      pravega-pravega-segmentstore-2
    Unready:
      pravega-bookie-2
  Ready Replicas:  8
  Replicas:        9
  Version History:
    0.6.0-2408.7312399
Events:
  Type   Reason         Age   From  Message
  ----   ------         ----  ----  -------
  Error  Upgrade Error  17s         Error Upgrading from version 0.6.0-2408.7312399 to 0.6.1-2419.5ae9098. failed to sync bookkeeper version. updating statefulset (pravega-bookie) failed due to progress deadline exceeded
```
Operator.yaml used:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pravega-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pravega-operator
  template:
    metadata:
      labels:
        name: pravega-operator
        component: pravega-operator
    spec:
      serviceAccountName: pravega-operator
      containers:
        - name: pravega-operator
          image: pravega/pravega-operator:0.4.3-rc1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - pravega-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pravega-operator"
```

Following was the pravega_manifest.yaml used:
[pravega_manifest.txt](https://github.com/pravega/pravega-operator/files/3931710/pravega_manifest.txt)

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

### Change log description
When checking for values updated in the `version` field it is important to consider the cluster state and then based on that decide if the updated value is correct or not.

### Purpose of the change
Fixes #309 

### What the code does
Checks for cluster state and version validation logic changes based on cluster state.
```
if ( cluster in pods ready state)
{ version change leads to upgrade, check upgrade compatibility matrix  }
else if (cluster in upgrade failed state)
{ version change should lead to rollback if (request version != last stable cluster version) reject request }
}
```
### How to verify it
Should be able to trigger rollback when version feild is updated to `0.6.1-2419.5ae9098`
when upgrade fails from version  `0.6.0-2408.7312399` to `0.6.1-2419.5ae9098`

### CODE REVIEW

File: pkg/webhook/webhook.go [hunk 1]
```diff
@@ -105,45 +103,55 @@ func (pwh *pravegaWebhookHandler) mutatePravegaVersion(ctx context.Context, p *p
...
-	nn := types.NamespacedName{
-		Namespace: p.Namespace,
-		Name:      p.Name,
-	}
-	err = pwh.client.Get(context.TODO(), nn, found)
-	if err != nil && !errors.IsNotFound(err) {
-		return fmt.Errorf("failed to obtain PravegaCluster resource: %v", err)
+	if p.Status.IsClusterInUpgradeFailedState() {
+		if requestVersion != p.Status.GetLastVersion() {
+			return fmt.Errorf("Rollback to version %s not supported. Only rollback to previous stable version is supported.", requestVersion)
```
Comment (SrishT) [inline pkg/webhook/webhook.go]: It would be better if we could add the previous stable version number here too.

Comment (pbelgundi) [reply pkg/webhook/webhook.go]: Done
