### PR TITLE
Issue 292: Operator fails to deploy Pravega 0.7

### LINKED ISSUE #292: Operator is failing to deploy Pravega version 0.7
### Description
Pravega operator fails to deploy pravega master version, that is `0.7`
Tried to deploy pravega version `0.7.0-2405.7c0c026` using the operator, but it is failing with the below error
```08:13:52  + kubectl create -f ./manifests/pravega/pravega_manifest.yaml
08:13:52  Error from server (InternalError): error when creating ./manifests/pravega/pravega_manifest.yaml: Internal error occurred: admission webhook "pravegawebhook.pravega.io" denied the request: unsupported Pravega cluster version 0.7.0-2405.7c0c026
```

### Importance

must-have

### Location

Operator code

### Suggestions for an improvement

Operator should support `pravega-0.7.0`

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
The pravega admission webhook restricts the deployment of Pravega cluster version `0.7` which is not expected.

### Purpose of the change
Fixes #292 

### What the code does
It adds `0.7` to the list of supported versions for the pravega admission webhook.

### How to verify it
Pravega version `0.7.0-2405.7c0c026` will be deployed successfully
```
$ kubectl get PravegaCluster
NAME          VERSION              DESIRED VERSION      DESIRED MEMBERS   READY MEMBERS   AGE
bar-pravega   0.7.0-2405.7c0c026   0.7.0-2405.7c0c026   5                 5               92m
```

### CODE REVIEW

File: pkg/webhook/webhook.go [hunk 1]
```diff
@@ -42,6 +42,7 @@ var (
 		"0.4.0": []string{"0.4.0"},
 		"0.5.0": []string{"0.5.0", "0.6.0"},
 		"0.6.0": []string{"0.6.0"},
```
Comment (pbelgundi) [inline pkg/webhook/webhook.go]: Need to add an entry for 0.7.0 against the 0.6.0 and 0.5.0 keys so that we can support upgrade from 0.6.0 to 0.7.0 and from 0.5.0 to 0.7.0.
Please also test this works

Comment (SrishT) [reply pkg/webhook/webhook.go]: done
