### PR TITLE
Issue 231:  Increase pravega-operator code coverage

### LINKED ISSUE #231: Increase pravega-operator code coverage to > 85%
### Description
Current code coverage is < 50% which is abysmal. 

### Importance
Low code coverage hinders with robust testing of changes and and does not allow us to fail fast.

### Location
Current statement coverage: 48.8% 

### Suggestions for an improvement
Add more tests to cover all possible code paths such that we get code coverage of > 85%

### PR DESCRIPTION
**Pull request by anishakj**
### Change log description

Increased the coverage of the packages v1alpha1, v1beta1 and util

### Purpose of the change

 Fixes #231

### What the code does

Added unit tests.

### How to verify it

Unit tests are passing

### CODE REVIEW

File: pkg/apis/pravega/v1alpha1/status_test.go [hunk 1]
```diff
@@ -23,6 +23,37 @@ var _ = Describe("PravegaCluster Status", func() {
...
+		It("should contains upgrade ready condition and it is false status", func() {
+			_, condition := p.Status.GetClusterCondition(v1alpha1.ClusterConditionUpgrading)
+			Ω(condition.Status).To(Equal(corev1.ConditionFalse))
+		})
+		It("should contains pods ready condition and it is false status", func() {
+			_, condition := p.Status.GetClusterCondition(v1alpha1.ClusterConditionError)
+			Ω(condition.Status).To(Equal(corev1.ConditionFalse))
+		})
+	})
+	Context("checking for version history", func() {
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/apis/pravega/v1alpha1/status_test.go:45]: Now i have added more versions to version history, and getLastversion should give last appended version

File: pkg/util/pravegacluster_test.go [hunk 2]
```diff
@@ -0,0 +1,264 @@
...
+				"-XX:+CrashOnOutOfMemoryError",
+				"-XX:+HeapDumpOnOutOfMemoryError",
+				"-XX:HeapDumpPath=/heap",
+				"-yy:mem",
+				"",
+			}
+
+			result = OverrideDefaultJVMOptions(jvmOpts, customOpts)
+			result1 = OverrideDefaultJVMOptions(jvmOpts, result1)
+			log.Printf("result is %v", result)
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/util/pravegacluster_test.go]: done

File: pkg/apis/pravega/v1alpha1/status_test.go [hunk 3]
```diff
@@ -73,12 +143,177 @@ var _ = Describe("PravegaCluster Status", func() {
...
+		})
+
+	})
+
+	Context("set pods Error condition  rollback failed to be true", func() {
+		BeforeEach(func() {
+			p.Status.SetErrorConditionFalse()
+			p.Status.SetErrorConditionTrue("RollbackFailed", " ")
+		})
+		It("should return rollback failed state to true using function", func() {
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/apis/pravega/v1alpha1/status_test.go:236]: done

File: pkg/apis/pravega/v1alpha1/status_test.go [hunk 4]
```diff
@@ -73,12 +143,177 @@ var _ = Describe("PravegaCluster Status", func() {
...
+				p.Status.SetRollbackConditionFalse()
+			})
+			It("should have pods rollback condition with false status", func() {
+				_, condition := p.Status.GetClusterCondition(v1alpha1.ClusterConditionRollback)
+				Ω(condition.Status).To(Equal(corev1.ConditionFalse))
+			})
+			It("should have pods rollback condition with false status using function", func() {
+				Ω(p.Status.IsClusterInRollbackState()).To(Equal(false))
+			})
+			It("Checking GetlastCondition function and It should return nil n as cluster not in Rollback state", func() {
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/apis/pravega/v1alpha1/status_test.go]: done

File: pkg/apis/pravega/v1alpha1/status_test.go [hunk 5]
```diff
@@ -73,12 +144,179 @@ var _ = Describe("PravegaCluster Status", func() {
...
+		})
+
+		It("should have pods Error condition with true status using function", func() {
+			Ω(p.Status.IsClusterInErrorState()).To(Equal(true))
+		})
+		It("should have pods Error condition with true status", func() {
+			_, condition := p.Status.GetClusterCondition(v1alpha1.ClusterConditionError)
+			Ω(condition.Status).To(Equal(corev1.ConditionTrue))
+			Ω(condition.Message).To(Equal(" "))
+			Ω(condition.Reason).To(Equal("RollbackFailed"))
```
Comment (SrishT) [inline pkg/apis/pravega/v1alpha1/status_test.go:251]: The Reason is being set to "some err" and assertions is checking for `Reason` to be `RollbackFailed` ?

File: pkg/apis/pravega/v1alpha1/pravegacluster_types_test.go [hunk 6]
```diff
@@ -42,30 +42,68 @@ var _ = Describe("PravegaCluster Types Spec", func() {
...
+			p.Spec.Version = "0.6.0"
+			p.WithDefaults()
+			p.Spec.Authentication = nil
+			p.Spec.TLS = nil
+		})
+		It("IsEnabled should return false", func() {
+			Ω(p.Spec.Authentication.IsEnabled()).To(Equal(false))
+		})
+		It("IsCaBundlePresent should return false", func() {
+
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/apis/pravega/v1alpha1/pravegacluster_types_test.go]: Done

File: pkg/apis/pravega/v1alpha1/status_test.go (hunk 5 above)
Comment (anishakj) [reply pkg/apis/pravega/v1alpha1/status_test.go:251]: we are setting reason as `RollbackFailed` at line no:234 in BeforeEach function

Comment (anishakj) [reply pkg/apis/pravega/v1alpha1/status_test.go]: > we are setting reason as `RollbackFailed` at line no:234 in BeforeEach function

I have changed the order of tests now.

File: pkg/controller/pravega/pravega_segmentstore_test.go [hunk 7]
```diff
@@ -356,10 +371,34 @@ var _ = Describe("PravegaSegmentstore", func() {
...
 					Ω(err).Should(BeNil())
 				})
+			})
+			Context("Create External service with external service type and access type empty", func() {
+				BeforeEach(func() {
+					p.Spec.Pravega.SegmentStoreExternalServiceType = ""
+					p.Spec.ExternalAccess.Type = ""
+					p.Spec.ExternalAccess.DomainName = "example"
+				})
+				It("should create external service", func() {
```
Comment (SrishT) [inline pkg/controller/pravega/pravega_segmentstore_test.go:382]: Could we remove this line?

File: pkg/controller/pravega/pravega_segmentstore_test.go [hunk 8]
```diff
@@ -356,10 +371,34 @@ var _ = Describe("PravegaSegmentstore", func() {
...
 
+					_ = pravega.MakeSegmentStoreExternalServices(p)
+					Ω(err).Should(BeNil())
```
Comment (SrishT) [inline pkg/controller/pravega/pravega_segmentstore_test.go:384]: since ServiceType was reset we can also check that it is set to default value here

File: pkg/controller/pravega/pravega_segmentstore_test.go [hunk 9]
```diff
@@ -356,10 +371,34 @@ var _ = Describe("PravegaSegmentstore", func() {
...
+				})
 			})
+			Context("Create External service with external service type empty and access type load balancer", func() {
+				BeforeEach(func() {
+					m := make(map[string]string)
+					p.Spec.Pravega.SegmentStoreServiceAnnotations = m
+					p.Spec.Pravega.SegmentStoreExternalServiceType = ""
+					p.Spec.ExternalAccess.Type = corev1.ServiceTypeLoadBalancer
```
Comment (SrishT) [inline pkg/controller/pravega/pravega_segmentstore_test.go:392]: SegmentStoreService type was anyways set to LoadBalancer in the BeforeEach. So lets not set ExternalAccess type to LoadBalancer here. Lets check if it is taking the Service type to the value of ExternalAccess.Type which is set to ClusterIP in the BeforeEach

File: pkg/util/pravegacluster_test.go [hunk 10]
```diff
@@ -0,0 +1,262 @@
...
+var _ = Describe("pravegacluster", func() {
+
+	Context("IsVersionBelow07", func() {
+		var result1, result2 bool
+		BeforeEach(func() {
+
+			result1 = IsVersionBelow07("0.7.1")
+			result2 = IsVersionBelow07("0.6.0")
+			IsVersionBelow07("666")
+			IsVersionBelow07("")
```
Comment (SrishT) [inline pkg/util/pravegacluster_test.go:35]: The result returned by these 2 is not stored or checked

File: pkg/controller/pravegacluster/upgrade_test.go [hunk 11]
```diff
@@ -221,6 +225,51 @@ var _ = Describe("Pravega Cluster Version Sync", func() {
...
+					foundPravega.Status.SetPodsReadyConditionTrue()
+					client.Update(context.TODO(), foundPravega)
+					_, _ = r.Reconcile(req)
+					foundPravega = &v1beta1.PravegaCluster{}
+					_ = client.Get(context.TODO(), req.NamespacedName, foundPravega)
+
+				})
+
+				It("should set upgrade condition reason and message to empty", func() {
+					_, upgradeCondition := foundPravega.Status.GetClusterCondition(pravegav1beta1.ClusterConditionUpgrading)
```
Comment (SrishT) [inline pkg/controller/pravegacluster/upgrade_test.go:246]: Can we check that UpgradeCondition is set to false as well, since `clearUpgradeStatus` would do that

File: pkg/controller/pravegacluster/upgrade_test.go [hunk 12]
```diff
@@ -221,6 +225,51 @@ var _ = Describe("Pravega Cluster Version Sync", func() {
...
+					foundPravega.Status.CurrentVersion = "0.7.0"
+					client.Update(context.TODO(), foundPravega)
+					_, _ = r.Reconcile(req)
+					foundPravega = &v1beta1.PravegaCluster{}
+					_ = client.Get(context.TODO(), req.NamespacedName, foundPravega)
+				})
+
+				It("should set the target version to empty", func() {
+
+					Ω(foundPravega.Status.TargetVersion).To(BeEquivalentTo(""))
```
Comment (SrishT) [inline pkg/controller/pravegacluster/upgrade_test.go:270]: Lets set Upgrade Condition to true in `BeforeEach` before calling Update(), and check that Upgrade Condition is also being set to false inside the assertion.

File: pkg/apis/pravega/v1alpha1/zz_generated.deepcopy_test.go [hunk 13]
```diff
@@ -0,0 +1,316 @@
...
+	. "github.com/onsi/ginkgo"
+	. "github.com/onsi/gomega"
+)
+
+var _ = Describe("PravegaCluster DeepCopy", func() {
+	Context("with defaults", func() {
+		var str1, str2 string
+		var str3, str4 v1.PullPolicy
+
+		var p1, p2 *v1alpha1.PravegaCluster
```
Comment (SrishT) [inline pkg/apis/pravega/v1alpha1/zz_generated.deepcopy_test.go:27]: Could we add all variables inside a `var` block
```
var (
   str1, str2 string
   ...
)
```

File: pkg/controller/pravega/pravega_segmentstore_test.go (hunk 8 above)
Comment (anishakj) [reply pkg/controller/pravega/pravega_segmentstore_test.go:383]: intent is to just to cover service is getting created

File: pkg/controller/pravega/pravega_segmentstore_test.go (hunk 9 above)
Comment (anishakj) [reply pkg/controller/pravega/pravega_segmentstore_test.go]: intent is to just to cover service is getting created in these case.

File: pkg/apis/pravega/v1beta1/pravegacluster_types_test.go [hunk 14]
```diff
@@ -67,5 +70,66 @@ var _ = Describe("PravegaCluster Types Spec", func() {
...
+
+		It("IsSecureSegmentStore should return false", func() {
+			Ω(p.Spec.TLS.IsSecureSegmentStore()).To(Equal(false))
+		})
+
+		It("IsCaBundlePresent should return false", func() {
+			Ω(p.Spec.TLS.IsCaBundlePresent()).To(Equal(false))
+		})
+
+		It("IsEnabled should return false", func() {
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/apis/pravega/v1beta1/pravegacluster_types_test.go]: done

File: pkg/apis/pravega/v1beta1/pravegacluster_types_test.go [hunk 15]
```diff
@@ -67,5 +70,66 @@ var _ = Describe("PravegaCluster Types Spec", func() {
...
+			p.Spec.Version = "0.6.0"
+			p.WithDefaults()
+			p.Spec.Authentication = nil
+			p.Spec.TLS = nil
+		})
+		It("IsEnabled should return false", func() {
+			Ω(p.Spec.Authentication.IsEnabled()).To(Equal(false))
+		})
+		It("IsCaBundlePresent should return false", func() {
+
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/apis/pravega/v1beta1/pravegacluster_types_test.go]: removed

File: pkg/apis/pravega/v1beta1/pravegacluster_types_test.go [hunk 16]
```diff
@@ -67,5 +70,66 @@ var _ = Describe("PravegaCluster Types Spec", func() {
...
+			Ω(p.Spec.TLS.IsSecureController()).To(Equal(false))
+		})
+	})
+	Context("checking volume claim template is present", func() {
+		BeforeEach(func() {
+			p.Spec.Version = "0.6.0"
+			p.WithDefaults()
+		})
+		It("should set volume claim template", func() {
+
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/apis/pravega/v1beta1/pravegacluster_types_test.go]: removed

File: pkg/apis/pravega/v1beta1/status_test.go [hunk 17]
```diff
@@ -72,13 +143,181 @@ var _ = Describe("PravegaCluster Status", func() {
...
+				})
+				It("Checking GetlastCondition function and It should return RollbackCondition as cluster in Rollback state", func() {
+					condition := p.Status.GetLastCondition()
+					Ω(string(condition.Type)).To(Equal(v1beta1.ClusterConditionRollback))
+				})
+				It("Checking ClusterInUpgradeFailedOrRollbackState and It should return true", func() {
+					Ω(p.Status.IsClusterInUpgradeFailedOrRollbackState()).To(Equal(true))
+				})
+
+				Context("set pods rollback condition to be false", func() {
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/apis/pravega/v1beta1/status_test.go]: done

File: pkg/apis/pravega/v1beta1/zz_generated_deepcopy_test.go [hunk 18]
```diff
@@ -0,0 +1,285 @@
...
+	. "github.com/onsi/ginkgo"
+	. "github.com/onsi/gomega"
+)
+
+var _ = Describe("PravegaCluster DeepCopy", func() {
+	Context("with defaults", func() {
+		var str1, str2 string
+		var str3, str4 v1.PullPolicy
+
+		var p1, p2 *v1beta1.PravegaCluster
```
[the remark this answers is not in the document]
Comment (anishakj) [reply pkg/apis/pravega/v1beta1/zz_generated_deepcopy_test.go]: done

File: pkg/controller/pravega/pravega_segmentstore_test.go (hunk 7 above)
Comment (anishakj) [reply pkg/controller/pravega/pravega_segmentstore_test.go]: done

File: pkg/util/pravegacluster_test.go (hunk 10 above)
Comment (anishakj) [reply pkg/util/pravegacluster_test.go]: done

File: pkg/controller/pravegacluster/upgrade_test.go (hunk 11 above)
Comment (anishakj) [reply pkg/controller/pravegacluster/upgrade_test.go:245]: done

File: pkg/controller/pravegacluster/upgrade_test.go (hunk 12 above)
Comment (anishakj) [reply pkg/controller/pravegacluster/upgrade_test.go:271]: done

File: pkg/apis/pravega/v1alpha1/zz_generated.deepcopy_test.go (hunk 13 above)
Comment (anishakj) [reply pkg/apis/pravega/v1alpha1/zz_generated.deepcopy_test.go]: done

File: pkg/controller/pravega/pravega_segmentstore_test.go (hunk 9 above)
Comment (anishakj) [reply pkg/controller/pravega/pravega_segmentstore_test.go]: Got it now, i have added the checks
