### PR TITLE
Issue-449: Rollback fails in case of only 1 Segment Store Pod

### LINKED ISSUE #449: Rollback fails in case of only 1 Segment Store Pod
### Description
When the upgrade of a pravega cluster containing a single segmentstore replica fails (due to upgrade to an invalid pravega version), the readiness check on the controller pods soon starts to fail.

```
NAME READY STATUS RESTARTS AGE
bookkeeper-bookie-0 1/1 Running 0 66m
bookkeeper-bookie-1 1/1 Running 0 66m
bookkeeper-bookie-2 1/1 Running 0 66m
bookkeeper-operator-cd5b76d74-frvp9 1/1 Running 0 8h
nfs-server-provisioner-1599135458-0 1/1 Running 0 8d
pravega-operator-5c5776fb84-bwhfb 1/1 Running 0 8h
pravega-pravega-controller-667b796659-ft85s 0/1 Running 0 64m
pravega-pravega-segment-store-0 0/1 ImagePullBackOff 0 60m
zookeeper-0 1/1 Running 0 67m
zookeeper-1 1/1 Running 0 67m
zookeeper-2 1/1 Running 0 66m
zookeeper-operator-55ccb88b87-r4l5j 1/1 Running 0 2d2h
```
Subsequently, even the rollback of the pravega cluster to its previous version fails.
 This happens only in case there is 1 ss pod and upgrade for that ss pod has failed and as not even one ss pod is available get request for system scope fails and when rollback happens the controller pod isn't marked ready for the same reason.

### Importance
should_have

### Location
upgrade.go file

### Suggestions for an improvement
In case of only 1 ss replica change the order of rollback, Rollback first the ss pod and then the controller pod.

### PR DESCRIPTION
**Pull request by Prabhaker24**
Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>

### Change log description
Rollback fails in case of only 1 Segment Store Pod

### Purpose of the change
Fixes #449 

### What the code does
This code changes the order of rollback in case of 1 ss i.e first the ss get's rollback then the controller which ensures readiness check doesn't fail and the rollback is successful.

### How to verify it
Deploy pravega with 1 ss pod and try and upgrade and fail the upgrade process then rollback the cluster and first ss should get rollback then the controller.

### CODE REVIEW

File: pkg/controller/pravegacluster/upgrade_test.go [hunk 1]
```diff
@@ -752,9 +752,9 @@ var _ = Describe("Pravega Cluster Version Sync", func() {
 					_ = client.Get(context.TODO(), req.NamespacedName, foundPravega)
 				})
 
-				It("should set rollback condition reason to UpdatingController and message to 0", func() {
+				It("should set rollback condition reason to UpdatingSegmentStore and message to 0", func() {
```
Comment (anishakj) [inline pkg/controller/pravegacluster/upgrade_test.go:755]: Could you please add a test case for rollback with more than one segment store replicas.

**Review by anishakj — CHANGES_REQUESTED** [review]

**Review by anishakj — APPROVED** [review]
LGTM

**Review by SrishT — APPROVED** [review]
LGTM
