### PR TITLE
Issue 611: Adding validation for authentication settings

### LINKED ISSUE #611: Enhance validation for authentication settings
### Description

Currently, if user has enabled authentication via `spec.Authentication.Enabled` but not provided correct options, Pravega will get deployed  and it fails to list streams

### Importance

 must-have

### Location

pkg/apis/pravega/v1beta1/pravegacluster_types.go

### Suggestions for an improvement

Add webhook validation to ensure authentication options are correct

### PR DESCRIPTION
**Pull request by anishakj**
Signed-off-by: anishakj <anisha.kj@dell.com>

### Change log description

Adding validation for authentication settings

### Purpose of the change

Fixes #611
### What the code does

If authentication is enabled,  webhook validation will  ensure
a. Pravega.Options["autoScale.controller.connect.security.auth.enable"]/p.Spec.Pravega.Options["autoScale.authEnabled"] is set to true
b. controller.security.auth.delegationToken.signingKey.basis is present
c. autoScale.security.auth.token.signingKey.basis is present
d. b and c are equal

If authentication is disabled. validation will ensure  Pravega.Options["autoScale.controller.connect.security.auth.enable"]/p.Spec.Pravega.Options["autoScale.authEnabled"] is set to false
### How to verify it

Verified by setting these options and installed pravega and saw that proper error message is displayed.

### CODE REVIEW

File: pkg/apis/pravega/v1beta1/pravegacluster_types.go [hunk 1]
```diff
@@ -1000,6 +1009,7 @@ func (p *PravegaCluster) ValidatePravegaVersion() error {
 	return nil
 }
 
+//
```
Comment (jkhalack) [inline pkg/apis/pravega/v1beta1/pravegacluster_types.go:1012]: Left over from some other commit?

File: pkg/apis/pravega/v1beta1/pravegacluster_types.go [hunk 2]
```diff
@@ -1216,6 +1226,50 @@ func (p *PravegaCluster) validateConfigMap() error {
...
+func (p *PravegaCluster) ValidateAuthenticationSettings() error {
+	if p.Spec.Authentication.Enabled == true {
+		newkey, ok := p.Spec.Pravega.Options["autoScale.controller.connect.security.auth.enable"]
+		oldkey := ""
+		if !ok {
+			oldkey, ok = p.Spec.Pravega.Options["autoScale.authEnabled"]
+		}
+		if !ok {
+			return fmt.Errorf("autoScale.controller.connect.security.auth.enable field is not present")
+		} else if newkey == "false" || oldkey == "false" {
```
Comment (jkhalack) [inline pkg/apis/pravega/v1beta1/pravegacluster_types.go:1240]: Should we rather be checking instead that one (or both) of them is set to `"true"` and the other is unset (or both are set to `"true"`)?

Comment (anishakj) [reply pkg/apis/pravega/v1beta1/pravegacluster_types.go:1240]: I am not sure if one of the keys is set to `true` and other is set to `false` which one will take precedence. I think second option will take precedence. But here .we are ensuring that both of the keys cannot be set to `false`.

Comment (jkhalack) [reply pkg/apis/pravega/v1beta1/pravegacluster_types.go:1239]: My concern was more about things like `"True"` or `"dummy"` (there is no validation)

Comment (anishakj) [reply pkg/apis/pravega/v1beta1/pravegacluster_types.go]: Made the changes to take care of that scenario and verified it. Please have a look

File: pkg/apis/pravega/v1beta1/pravegacluster_types.go [hunk 3]
```diff
@@ -1216,6 +1225,59 @@ func (p *PravegaCluster) validateConfigMap() error {
...
+			}
+		}
+		if oldkey == "" {
+			if newkey != "true" {
+				return fmt.Errorf("autoScale.controller.connect.security.auth.enable should be set to true")
+			}
+		}
+		if oldkey != "" && newkey != "" {
+			if newkey != "true" || oldkey != "true" {
+				return fmt.Errorf("autoScale.controller.connect.security.auth.enable/autoScale.authEnabled should be set to true")
```
Comment (nishant-yt) [inline pkg/apis/pravega/v1beta1/pravegacluster_types.go:1250]: Since at this point user is setting both the Options , we can modify the Error message as:
`Both autoScale.controller.connect.security.auth.enable and autoScale.authEnabled should be set to true`

**Review by nishant-yt — APPROVED** [review]
LGTM

File: pkg/apis/pravega/v1beta1/pravegacluster_types.go [hunk 4]
```diff
@@ -1216,6 +1225,59 @@ func (p *PravegaCluster) validateConfigMap() error {
...
+		if oldkey == "" {
+			if newkey != "true" {
+				return fmt.Errorf("autoScale.controller.connect.security.auth.enable should be set to true")
+			}
+		}
+		if oldkey != "" && newkey != "" {
+			if newkey != "true" || oldkey != "true" {
+				return fmt.Errorf("Both autoScale.controller.connect.security.auth.enable and autoScale.authEnabled should be set to true")
+			}
+		}
```
Comment (jkhalack) [inline pkg/apis/pravega/v1beta1/pravegacluster_types.go:1252]: The logic here won't allow disabling the authentication, which does not seem to be the purpose of the current PR.

**Review by jkhalack — CHANGES_REQUESTED** [review]

File: pkg/apis/pravega/v1beta1/pravegacluster_types.go (hunk 4 above)
Comment (anishakj) [reply pkg/apis/pravega/v1beta1/pravegacluster_types.go:1252]: @jkhalack  we can disable authentication by making ```authentication:
  enabled: false```  and in that case we are just ensuring option fields are not set to `true`

Comment (jkhalack) [reply pkg/apis/pravega/v1beta1/pravegacluster_types.go:1252]: We are not getting to line 1270 unless we set either one or both of `autoScale.authEnabled`, `autoScale.controller.connect.security.auth.enable` keys to something.
None of the above keys can be set to `false` and allow the logic slip to line 1270.
