### PR TITLE
Issue 100: Delete PVC when scaling down

### LINKED ISSUE #100: Journal,Cache and ledgers not getting removed for scaled down bookie and segmentstore using kubectl edit
**Journal,Cache and ledgers not getting removed for scaled down bookie and segmentstore using kubectl edit**

Steps to reproduce:
```
1. Scale up segmentstore and Bookie using kubectl edit <cluster name>
2. Scaled down segmentstore and Bookie using kubectl edit <cluster name>
```
Snip:
```
Scaled up to 6 bookie and segstore:
[root@manager1 ~]# kubectl get po --all-namespaces
NAMESPACE          NAME                                                        READY     STATUS    RESTARTS   AGE
nautilus-pravega   nautilus-bookie-0                                           1/1       Running   0          5m
nautilus-pravega   nautilus-bookie-1                                           1/1       Running   0          5m
nautilus-pravega   nautilus-bookie-2                                           1/1       Running   0          5m
nautilus-pravega   nautilus-bookie-3                                           1/1       Running   0          13s
nautilus-pravega   nautilus-bookie-4                                           1/1       Running   0          13s
nautilus-pravega   nautilus-bookie-5                                           1/1       Running   0          13s
nautilus-pravega   nautilus-segmentstore-0                                     1/1       Running   2          5m
nautilus-pravega   nautilus-segmentstore-1                                     1/1       Running   0          5m
nautilus-pravega   nautilus-segmentstore-2                                     1/1       Running   0          5m
nautilus-pravega   nautilus-segmentstore-3                                     1/1       Running   0          13s
nautilus-pravega   nautilus-segmentstore-4                                     1/1       Running   0          13s
nautilus-pravega   nautilus-segmentstore-5                                     1/1       Running   0          13s

Scaled down to 3:

[root@manager1 ~]# kubectl edit PravegaCluster nautilus -n nautilus-pravega
pravegacluster.pravega.pravega.io "nautilus" edited

[root@manager1 ~]# kubectl get po --all-namespaces
NAMESPACE          NAME                                                        READY     STATUS    RESTARTS   AGE
nautilus-pravega   nautilus-bookie-0                                           1/1       Running   0          7m
nautilus-pravega   nautilus-bookie-1                                           1/1       Running   0          7m
nautilus-pravega   nautilus-bookie-2                                           1/1       Running   0          7m
nautilus-pravega   nautilus-segmentstore-0                                     1/1       Running   2          7m
nautilus-pravega   nautilus-segmentstore-1                                     1/1       Running   0          7m
nautilus-pravega   nautilus-segmentstore-2                                     1/1       Running   0          7m

[root@manager1 ~]# kubectl get pvc --all-namespaces
NAMESPACE          NAME                                            STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nautilus-pravega   cache-nautilus-segmentstore-0                   Bound     pvc-e2c9c6f3-f2cb-11e8-b82a-005056bd38d8   100Gi      RWO            standard       3h
nautilus-pravega   cache-nautilus-segmentstore-1                   Bound     pvc-e2ced9b5-f2cb-11e8-b82a-005056bd38d8   100Gi      RWO            standard       3h
nautilus-pravega   cache-nautilus-segmentstore-2                   Bound     pvc-e2d39f91-f2cb-11e8-b82a-005056bd38d8   100Gi      RWO            standard       3h
nautilus-pravega   cache-nautilus-segmentstore-3                   Bound     pvc-49da332c-f2de-11e8-b82a-005056bd38d8   100Gi      RWO            standard       58m
nautilus-pravega   cache-nautilus-segmentstore-4                   Bound     pvc-b67443d3-f2e0-11e8-b82a-005056bd38d8   100Gi      RWO            standard       41m
nautilus-pravega   cache-nautilus-segmentstore-5                   Bound     pvc-b67443d3-f2e0-11e8-b82a-005056bd38d8   100Gi      RWO            standard       42m

nautilus-pravega   journal-nautilus-bookie-0                       Bound     pvc-e2a051c1-f2cb-11e8-b82a-005056bd38d8   250Gi      RWO            standard       3h
nautilus-pravega   journal-nautilus-bookie-1                       Bound     pvc-e2a99036-f2cb-11e8-b82a-005056bd38d8   250Gi      RWO            standard       3h
nautilus-pravega   journal-nautilus-bookie-2                       Bound     pvc-e2b78679-f2cb-11e8-b82a-005056bd38d8   250Gi      RWO            standard       3h
nautilus-pravega   journal-nautilus-bookie-3                       Bound     pvc-49d3457c-f2de-11e8-b82a-005056bd38d8   250Gi      RWO            standard       58m
nautilus-pravega   journal-nautilus-bookie-4                       Bound     pvc-f1ee7509-f2df-11e8-b82a-005056bd38d8   250Gi      RWO            standard       46m
nautilus-pravega   journal-nautilus-bookie-5                       Bound     pvc-32263446-f2e0-11e8-b82a-005056bd38d8   250Gi      RWO            standard       45m

nautilus-pravega   ledger-nautilus-bookie-0                        Bound     pvc-e2a1b439-f2cb-11e8-b82a-005056bd38d8   250Gi      RWO            standard       3h
nautilus-pravega   ledger-nautilus-bookie-1                        Bound     pvc-e2b1001e-f2cb-11e8-b82a-005056bd38d8   250Gi      RWO            standard       3h
nautilus-pravega   ledger-nautilus-bookie-2                        Bound     pvc-e2bd4476-f2cb-11e8-b82a-005056bd38d8   250Gi      RWO            standard       3h
nautilus-pravega   ledger-nautilus-bookie-3                        Bound     pvc-49d3fff1-f2de-11e8-b82a-005056bd38d8   250Gi      RWO            standard       58m
nautilus-pravega   ledger-nautilus-bookie-4                        Bound     pvc-f1ef09f7-f2df-11e8-b82a-005056bd38d8   250Gi      RWO            standard       46m
nautilus-pravega   ledger-nautilus-bookie-5                        Bound     pvc-32268e3a-f2e0-11e8-b82a-005056bd38d8   250Gi      RWO            standard       45m
```

### PR DESCRIPTION
**Pull request by Tristan1900**
## Change log description

- Delete persistent volumes in bookie and segment store when scaling down.

- According to K8s documents, Pods are deleted in ordinal sequence when scaling down. 

- We just need to keep persistent volume claims with smaller ordinal number compared to replicas of statefulset.
## Purpose of the change
Fix #100

## How to test the change
Checkout to source branch, follow the instructions on the README.md to deploy a Pravega Cluster.

After you have a running Pravega Cluster, edit the replicas number in bookkeeper or segment store
```
$kubectl edit pravegacluster pravega
```
A yaml file will pop up, you can directly edit it with your text editor. Save the change and exit, k8s will automatically update your change.

Check Pod number and persistent volume claims number to see if they are matched with your change. In this case, I change the segment store replicas to 4. 
```
$kubectl get pod
NAME                                          READY   STATUS    RESTARTS   AGE
clunky-sasquatch-nfs-server-provisioner-0     1/1     Running   0          4d18h
example-0                                     1/1     Running   0          8m54s
example-1                                     1/1     Running   0          7m56s
example-2                                     1/1     Running   0          6m57s
pravega-bookie-0                              1/1     Running   0          11m
pravega-bookie-1                              1/1     Running   0          11m
pravega-bookie-2                              1/1     Running   0          11m
pravega-pravega-controller-576cfb874c-gpthz   1/1     Running   0          11m
pravega-pravega-segmentstore-0                1/1     Running   0          11m
pravega-pravega-segmentstore-1                1/1     Running   0          11m
pravega-pravega-segmentstore-2                1/1     Running   0          11m
pravega-pravega-segmentstore-3                0/1     Pending   0          2s
pravega-search-operator-6d999b8cbc-hzcvf      1/1     Running   0          3d1h
zookeeper-operator-789696cc4b-2k5r8           1/1     Running   0          4d18h


$kubectl get pvc
NAME                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cache-pravega-pravega-segmentstore-0   Bound    pvc-92ac400a-fc16-11e8-828a-42010a8000ad   20Gi       RWO            standard       13m
cache-pravega-pravega-segmentstore-1   Bound    pvc-92b01d1b-fc16-11e8-828a-42010a8000ad   20Gi       RWO            standard       13m
cache-pravega-pravega-segmentstore-2   Bound    pvc-92bb6a7a-fc16-11e8-828a-42010a8000ad   20Gi       RWO            standard       13m
cache-pravega-pravega-segmentstore-3   Bound    pvc-33030280-fc18-11e8-828a-42010a8000ad   20Gi       RWO            standard       114s
data-example-0                         Bound    pvc-dc6bfe6e-fc16-11e8-828a-42010a8000ad   20Gi       RWO            standard       11m
data-example-1                         Bound    pvc-18f79f1f-fc17-11e8-828a-42010a8000ad   20Gi       RWO            standard       9m48s
data-example-2                         Bound    pvc-3c1379b9-fc17-11e8-828a-42010a8000ad   20Gi       RWO            standard       8m49s
journal-pravega-bookie-0               Bound    pvc-92380150-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       13m
journal-pravega-bookie-1               Bound    pvc-923eafcb-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       13m
journal-pravega-bookie-2               Bound    pvc-924a8278-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       13m
ledger-pravega-bookie-0                Bound    pvc-9238d7b9-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       13m
ledger-pravega-bookie-1                Bound    pvc-9241afe2-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       13m
ledger-pravega-bookie-2                Bound    pvc-9247d563-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       13m
pravega-tier2                          Bound    pvc-d6a3fa57-fc16-11e8-828a-42010a8000ad   50Gi       RWX            nfs            11m

```

Then use the same way to edit the replicas to scale down the cluster size. 
```
$kubectl edit pravegacluster pravega
$kubectl get pod
NAME                                          READY   STATUS    RESTARTS   AGE
clunky-sasquatch-nfs-server-provisioner-0     1/1     Running   0          4d19h
example-0                                     1/1     Running   0          40m
example-1                                     1/1     Running   0          39m
example-2                                     1/1     Running   0          38m
pravega-bookie-0                              1/1     Running   0          43m
pravega-bookie-1                              1/1     Running   0          43m
pravega-bookie-2                              1/1     Running   0          43m
pravega-pravega-controller-576cfb874c-gpthz   1/1     Running   0          43m
pravega-pravega-segmentstore-0                1/1     Running   0          43m
pravega-pravega-segmentstore-1                1/1     Running   0          43m
pravega-pravega-segmentstore-2                1/1     Running   0          43m
pravega-search-operator-6d999b8cbc-hzcvf      1/1     Running   0          3d1h
zookeeper-operator-789696cc4b-2k5r8           1/1     Running   0          4d19h

$kubectl get pvc
NAME                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cache-pravega-pravega-segmentstore-0   Bound    pvc-92ac400a-fc16-11e8-828a-42010a8000ad   20Gi       RWO            standard       14m
cache-pravega-pravega-segmentstore-1   Bound    pvc-92b01d1b-fc16-11e8-828a-42010a8000ad   20Gi       RWO            standard       14m
cache-pravega-pravega-segmentstore-2   Bound    pvc-92bb6a7a-fc16-11e8-828a-42010a8000ad   20Gi       RWO            standard       14m
data-example-0                         Bound    pvc-dc6bfe6e-fc16-11e8-828a-42010a8000ad   20Gi       RWO            standard       12m
data-example-1                         Bound    pvc-18f79f1f-fc17-11e8-828a-42010a8000ad   20Gi       RWO            standard       10m
data-example-2                         Bound    pvc-3c1379b9-fc17-11e8-828a-42010a8000ad   20Gi       RWO            standard       9m32s
journal-pravega-bookie-0               Bound    pvc-92380150-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       14m
journal-pravega-bookie-1               Bound    pvc-923eafcb-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       14m
journal-pravega-bookie-2               Bound    pvc-924a8278-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       14m
ledger-pravega-bookie-0                Bound    pvc-9238d7b9-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       14m
ledger-pravega-bookie-1                Bound    pvc-9241afe2-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       14m
ledger-pravega-bookie-2                Bound    pvc-9247d563-fc16-11e8-828a-42010a8000ad   10Gi       RWO            standard       14m
pravega-tier2                          Bound    pvc-d6a3fa57-fc16-11e8-828a-42010a8000ad   50Gi       RWX            nfs            12m
```

You can see the number of pvc in segment store is reduced to 3. 

Signed-off-by: wenqi Wenqi.Mou@emc.com

### CODE REVIEW

**Comment by Tristan1900** [comment]
@adrianmo Thanks for the update, I think yours is the right way to do. It also works as expected.

File: pkg/controller/pravegacluster/pravegacluster_controller.go [hunk 1]
```diff
@@ -299,3 +310,39 @@ func (r *ReconcilePravegaCluster) syncControllerSize(p *pravegav1alpha1.PravegaC
 	}
 	return nil
 }
+
+func (r *ReconcilePravegaCluster) syncStatefulSetPvc(sts *appsv1.StatefulSet) error {
+	selector, err := metav1.LabelSelectorAsSelector(&metav1.LabelSelector{
+		MatchLabels: sts.Spec.Template.Labels,
+	})
+	if err != nil {
+		return err
```
Comment (fpj) [inline pkg/controller/pravegacluster/pravegacluster_controller.go]: To be consistent, let's add an error message like here:

https://github.com/pravega/pravega-operator/pull/107/files#diff-d4ac6e435ae9f4544a5bc08fcf19c3ecR278
https://github.com/pravega/pravega-operator/pull/107/files#diff-d4ac6e435ae9f4544a5bc08fcf19c3ecR290

File: pkg/util/pravegacluster.go [hunk 2]
```diff
@@ -79,3 +81,17 @@ func LabelsForPravegaCluster(pravegaCluster *v1alpha1.PravegaCluster, component
 func PravegaControllerServiceURL(pravegaCluster v1alpha1.PravegaCluster) string {
 	return fmt.Sprintf("tcp://%v.%v:%v", ServiceNameForController(pravegaCluster.Name), pravegaCluster.Namespace, "9090")
 }
+
+func PvcIsOrphan(stsPvcName string, replicas int32) bool {
+	index := strings.LastIndexAny(stsPvcName, "-")
```
Comment (fpj) [inline pkg/util/pravegacluster.go]: Can the pvc name contain another occurrence of `-` that could confuse this logic?

File: pkg/util/pravegacluster.go [hunk 3]
```diff
@@ -79,3 +81,17 @@ func LabelsForPravegaCluster(pravegaCluster *v1alpha1.PravegaCluster, component
...
+	if index == -1 {
+		return false
+	}
+
+	ordinal, err := strconv.Atoi(stsPvcName[index+1:])
+	if err != nil {
+		return false
+	}
+
+	return int32(ordinal) >= replicas
```
Comment (fpj) [inline pkg/util/pravegacluster.go]: I think the ordinal can be zero and replica is at least one. I'm not sure this logic is correct.

File: pkg/controller/pravegacluster/pravegacluster_controller.go (hunk 1 above)
Comment (Tristan1900) [reply pkg/controller/pravegacluster/pravegacluster_controller.go]: Right I will modify that right now. Thanks

File: pkg/util/pravegacluster.go (hunk 2 above)
Comment (Tristan1900) [reply pkg/util/pravegacluster.go]: Good point. If a pvc is started by a statefulset, it will have a name in this format [pvcName]-[statfulsetName]-[ordinal]. So I think there won't be any more - occur.

File: pkg/util/pravegacluster.go (hunk 3 above)
Comment (Tristan1900) [reply pkg/util/pravegacluster.go]: Not quite sure what the problem is.
Ordinal being zero means the current number of pvc is 1. And replicas being 1 means the current target number of pvc is 1, which is just fine in this case. So 0 >= 1 is false and this pvc is not orphan. 
If ordinal is 1 and replicas is 1, then we have pvc number being 2 and target number of pvc being 1. The pvc with ordinal 1 shoud be deleted. So 1 >= 1 will return true. 
BTW ordinal is started from 0.

File: pkg/util/pravegacluster.go (hunk 2 above)
Comment (adrianmo) [reply pkg/util/pravegacluster.go]: Correct. StatefulSet PVC names always end with `-` + an ordinal number by design. They can contain more `-`, but the rightmost `-` will always be the separator, and that's what we capture in the `strings.LastIndexAny` function.

**Comment by adrianmo** [comment]
[Operator: Delete PVC when scaling down](https://trello.com/c/wcTbb368/62-operator-delete-pvc-when-scaling-down)

**Comment by Tristan1900** [comment]
Test is added. This PR is ready for the second review.

**Comment by adrianmo** [comment]
@fpj can you please review the PR? Thanks.
